const electron = require('electron')

const invoke = (channel, ...args) => electron.ipcRenderer.invoke(channel, ...args)
const on = (channel, listener) => {
  const wrapped = (_event, payload) => listener(payload)
  electron.ipcRenderer.on(channel, wrapped)
  return () => electron.ipcRenderer.removeListener(channel, wrapped)
}

electron.contextBridge.exposeInMainWorld('gameDesignToolsDesktop', {
  selectPersonalSpaceDirectory: () => invoke('personal-space:select-directory'),
  registerPersonalSpaceDirectory: (rootPath) => invoke('personal-space:register-directory', rootPath),
  ensurePersonalSpaceDirectory: (parentPath, name, options) => invoke('personal-space:ensure-directory', parentPath, name, options),
  getPersonalSpaceFile: (parentPath, name, options) => invoke('personal-space:get-file', parentPath, name, options),
  readPersonalSpaceFile: (filePath) => invoke('personal-space:read-file', filePath),
  writePersonalSpaceFile: (filePath, data) => invoke('personal-space:write-file', filePath, data),
  removePersonalSpaceEntry: (parentPath, name) => invoke('personal-space:remove-entry', parentPath, name),
  saveFile: (fileName, data) => invoke('file:save', fileName, data),
  openPath: (targetPath) => invoke('shell:open-path', targetPath),
  getAppUpdateStatus: () => invoke('app-update:get-status'),
  checkForAppUpdates: () => invoke('app-update:check'),
  installAppUpdate: () => invoke('app-update:install'),
  onAppUpdateStatus: (listener) => on('app-update:status', listener),
  detectHardware: () => invoke('hardware:detect'),
  runVoxcpmSetup: (options) => invoke('voxcpm:run-setup', options),
  queryVoxcpmSetupStatus: () => invoke('voxcpm:setup-status'),
  controlVoxcpmService: (action) => invoke('voxcpm:service', action),
  queryUpscaleStatus: () => invoke('upscayl:status'),
  installUpscaleRuntime: (options) => invoke('upscayl:install', options),
  upscaleImage: (options) => invoke('upscayl:upscale', options),
  onUpscaleInstallProgress: (listener) => on('upscayl:install-progress', listener),
  listProjectConnectionProfiles: (type) => invoke('project-profile:list', type),
  getProjectConnectionProfile: (profileId) => invoke('project-profile:get', profileId),
  saveProjectConnectionProfile: (input) => invoke('project-profile:save', input),
  deleteProjectConnectionProfile: (profileId) => invoke('project-profile:delete', profileId),
  verifyProjectDatabaseProfile: (profileId) => invoke('project-profile:verify-database', profileId),
  verifyProjectDatabaseProfileDraft: (input, profileId) => invoke('project-profile:verify-database-draft', input, profileId),
  initializeProjectDatabaseSchema: (profileId, dialect) => invoke('project-profile:initialize-database-schema', profileId, dialect),
  verifyProjectKodoProfile: (profileId, projectId) => invoke('project-profile:verify-kodo', profileId, projectId),
  verifyProjectKodoProfileDraft: (input, projectId, profileId) => invoke('project-profile:verify-kodo-draft', input, projectId, profileId),
  initializeLocalProjectRepository: () => invoke('project-local-repository:initialize'),
  createLocalProject: (input) => invoke('project-local-repository:create-project', input),
  createLocalRemoteProject: (input) => invoke('project-local-repository:create-remote-project', input),
  updateLocalProject: (projectId, input) => invoke('project-local-repository:update-project', projectId, input),
  listLocalProjects: () => invoke('project-local-repository:list-projects'),
  getLocalProject: (projectId) => invoke('project-local-repository:get-project', projectId),
  importLocalProjectRows: (rows) => invoke('project-local-repository:import-rows', rows),
  exportLocalProjectRows: (projectId) => invoke('project-local-repository:export-rows', projectId),
  listLocalProjectAssets: (projectId) => invoke('project-local-repository:list-assets', projectId),
  addLocalProjectCleanupTasks: (tasks) => invoke('project-local-repository:add-cleanup-tasks', tasks),
  listLocalProjectCleanupTasks: (projectId) => invoke('project-local-repository:list-cleanup-tasks', projectId),
  deleteLocalProject: (projectId) => invoke('project-local-repository:delete-project', projectId),
  putLocalProjectObject: (objectKey, data, mimeType) => invoke('project-local-object:put', objectKey, data, mimeType),
  getLocalProjectObject: (objectKey) => invoke('project-local-object:get', objectKey),
  deleteLocalProjectObject: (objectKey) => invoke('project-local-object:delete', objectKey),
  getProjectAssetCacheResource: (ref, expectedFingerprint) => invoke('project-asset-cache:get', ref, expectedFingerprint),
  putProjectAssetCacheResource: (ref, fingerprint, data, mimeType) => invoke('project-asset-cache:put', ref, fingerprint, data, mimeType),
  deleteProjectAssetCacheResource: (ref) => invoke('project-asset-cache:delete-resource', ref),
  deleteProjectAssetCacheForProject: (projectId) => invoke('project-asset-cache:delete-project', projectId),
  createRemoteProject: (input) => invoke('project-remote-repository:create-project', input),
  updateRemoteProject: (projectId, input, databaseProfileId) => invoke('project-remote-repository:update-project', projectId, input, databaseProfileId),
  listRemoteProjects: (databaseProfileId) => invoke('project-remote-repository:list-projects', databaseProfileId),
  getRemoteProject: (projectId, databaseProfileId) => invoke('project-remote-repository:get-project', projectId, databaseProfileId),
  importRemoteProjectRows: (rows, databaseProfileId) => invoke('project-remote-repository:import-rows', rows, databaseProfileId),
  exportRemoteProjectRows: (projectId, databaseProfileId) => invoke('project-remote-repository:export-rows', projectId, databaseProfileId),
  listRemoteProjectAssets: (projectId, databaseProfileId) => invoke('project-remote-repository:list-assets', projectId, databaseProfileId),
  addRemoteProjectCleanupTasks: (tasks, databaseProfileId) => invoke('project-remote-repository:add-cleanup-tasks', tasks, databaseProfileId),
  listRemoteProjectCleanupTasks: (projectId, databaseProfileId) => invoke('project-remote-repository:list-cleanup-tasks', projectId, databaseProfileId),
  deleteRemoteProject: (projectId, databaseProfileId) => invoke('project-remote-repository:delete-project', projectId, databaseProfileId),
  putProjectKodoObject: (profileId, objectKey, data, mimeType) => invoke('project-kodo-object:put', profileId, objectKey, data, mimeType),
  getProjectKodoObject: (profileId, objectKey) => invoke('project-kodo-object:get', profileId, objectKey),
  deleteProjectKodoObject: (profileId, objectKey) => invoke('project-kodo-object:delete', profileId, objectKey),
})
