const assetTableDefinitions = {
  asset_groups: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'kind',
      'name',
      'starred',
      'sort_order',
      'created_at',
      'updated_at',
    ],
  },
  assets: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'kind',
      'asset_subtype',
      'group_id',
      'name',
      'dialogue_text',
      'source_key',
      'primary_resource_id',
      'primary_object_key',
      'primary_file_name',
      'primary_mime_group',
      'primary_mime_type',
      'primary_extension',
      'primary_size_bytes',
      'primary_hash_sha256',
      'sprite_index_resource_id',
      'sprite_index_object_key',
      'sprite_index_file_name',
      'sprite_index_mime_type',
      'sprite_index_size_bytes',
      'sprite_index_hash_sha256',
      'cover_resource_id',
      'cover_object_key',
      'cover_file_name',
      'cover_mime_type',
      'cover_size_bytes',
      'cover_hash_sha256',
      'sprite_frame_width',
      'sprite_frame_height',
      'sprite_sheet_width',
      'sprite_sheet_height',
      'sprite_fps',
      'sprite_frame_count',
      'created_at',
      'updated_at',
      'metadata_json',
    ],
  },
  characters: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'name',
      'starred',
      'sort_order',
      'created_at',
      'updated_at',
    ],
  },
  character_asset_links: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'character_id',
      'asset_id',
      'column_kind',
      'sort_order',
      'created_at',
      'updated_at',
    ],
  },
  storyboard_groups: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'name',
      'starred',
      'created_at',
      'updated_at',
    ],
  },
  storyboard_voice_entries: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'storyboard_id',
      'asset_id',
      'character_id',
      'text',
      'start_offset_us',
      'sort_order',
      'created_at',
      'updated_at',
    ],
  },
  asset_relations: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'source_asset_id',
      'target_asset_id',
      'relation_type',
      'created_at',
    ],
  },
}

const assetRowSetTables = [
  ['assetGroups', 'asset_groups'],
  ['assets', 'assets'],
  ['characters', 'characters'],
  ['characterAssetLinks', 'character_asset_links'],
  ['storyboardGroups', 'storyboard_groups'],
  ['storyboardVoiceEntries', 'storyboard_voice_entries'],
  ['assetRelations', 'asset_relations'],
]

module.exports = {
  assetRowSetTables,
  assetTableDefinitions,
}
