const documentTableDefinitions = {
  document_collections: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'name',
      'description',
      'source_type',
      'status',
      'record_count',
      'node_count',
      'edge_count',
      'created_at',
      'updated_at',
      'imported_at',
      'metadata_json',
    ],
  },
  document_sources: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'role',
      'file_name',
      'mime_group',
      'mime_type',
      'extension',
      'size_bytes',
      'hash_sha256',
      'encoding',
      'created_at',
      'metadata_json',
    ],
  },
  document_source_contents: {
    conflictColumns: ['source_id'],
    columns: [
      'source_id',
      'project_id',
      'collection_id',
      'content_text',
      'content_encoding',
      'size_bytes',
      'hash_sha256',
      'created_at',
      'metadata_json',
    ],
  },
  document_records: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'source_id',
      'external_id',
      'record_type',
      'title',
      'description',
      'category_1',
      'category_2',
      'category_3',
      'place_path',
      'book_title',
      'chapter_title',
      'version_title',
      'usage_text',
      'effect_text',
      'source_url',
      'search_text',
      'created_at',
      'updated_at',
      'metadata_json',
    ],
  },
  document_nodes: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'external_id',
      'node_type',
      'label',
      'description',
      'search_text',
      'created_at',
      'updated_at',
      'metadata_json',
    ],
  },
  document_edges: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'external_id',
      'source_node_id',
      'target_node_id',
      'edge_type',
      'label',
      'weight',
      'source_kind',
      'created_at',
      'metadata_json',
    ],
  },
  document_node_record_links: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'node_id',
      'record_id',
      'link_role',
      'created_at',
    ],
  },
  document_edge_record_links: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'edge_id',
      'record_id',
      'created_at',
    ],
  },
  document_import_runs: {
    conflictColumns: ['id'],
    columns: [
      'id',
      'project_id',
      'collection_id',
      'source_type',
      'status',
      'started_at',
      'finished_at',
      'total_records',
      'total_nodes',
      'total_edges',
      'imported_records',
      'imported_nodes',
      'imported_edges',
      'error_message',
      'report_json',
    ],
  },
}

const documentRowSetTables = [
  ['documentCollections', 'document_collections'],
  ['documentSources', 'document_sources'],
  ['documentSourceContents', 'document_source_contents'],
  ['documentRecords', 'document_records'],
  ['documentNodes', 'document_nodes'],
  ['documentEdges', 'document_edges'],
  ['documentNodeRecordLinks', 'document_node_record_links'],
  ['documentEdgeRecordLinks', 'document_edge_record_links'],
  ['documentImportRuns', 'document_import_runs'],
]

module.exports = {
  documentRowSetTables,
  documentTableDefinitions,
}
