import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

test('home voice card describes Gradio instead of stale vLLM REST output', () => {
  const source = readFileSync('src/appNavigation.ts', 'utf8')

  assert.doesNotMatch(source, /vLLM/)
  assert.doesNotMatch(source, /\/v1\/audio\/speech/)
  assert.match(source, /Gradio/)
  assert.match(source, /gradio_client/)
})

test('voice history library renders outside the connected-only generator branch', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceLibraryPanel.tsx', 'utf8')
  const styleSource = readFileSync('src/components/VoiceDeploymentWorkspace/voiceDeployment.library.css', 'utf8')

  assert.match(source, /\{workspace\.connected \? \([\s\S]*renderVoiceLibraryPanel\('sticky'\)[\s\S]*\) : \([\s\S]*renderVoiceLibraryPanel\('embedded'\)/)
  assert.match(source, /const renderVoiceLibraryPanel = \(/)
  assert.match(source, /libraryVariant=\{libraryVariant\}/)
  assert.match(panelSource, /libraryVariant/)
  assert.match(panelSource, /voice-library-\$\{libraryVariant\}/)
  assert.match(styleSource, /\.voice-library-sticky/)
  assert.match(styleSource, /\.voice-library-embedded/)
})

test('voice records can be collected into project space assets', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const workspaceHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentWorkspace.ts', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceProjectSpaceActions.ts', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceLibraryPanel.tsx', 'utf8')
  const listSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceRecordLists.tsx', 'utf8')
  const collectorSource = readFileSync('src/components/VoiceDeploymentWorkspace/voicePersonalSpaceCollector.ts', 'utf8')

  assert.match(listSource, /收藏到项目空间/)
  assert.match(listSource, /personalSpaceCollectEnabled/)
  assert.match(listSource, /personalSpaceCollectDisabledReason/)
  assert.match(listSource, /disabled=\{!personalSpaceCollectEnabled\}/)
  assert.match(listSource, /收藏并关联角色/)
  assert.match(listSource, /收藏并关联特效/)
  assert.match(listSource, /收藏并关联剧情/)
  assert.match(listSource, /record-collect-action/)
  assert.match(listSource, /aria-label="展开收藏关联方式"/)
  assert.doesNotMatch(listSource, /Dropdown\.Button/)
  assert.match(workspaceHookSource, /personalSpaceVoiceAssets/)
  assert.match(panelSource, /label: `项目空间 \$\{personalSpaceVoiceAssets\.length\}`/)
  assert.match(hookSource, /collectVoiceRecordToPersonalSpace/)
  assert.match(hookSource, /readCurrentProjectSpaceState/)
  assert.match(hookSource, /persistCurrentProjectSpaceState/)
  assert.doesNotMatch(source, /writeCurrentProjectSpaceState/)
  assert.match(hookSource, /from '\.\/voicePersonalSpaceCollector'/)
  assert.match(collectorSource, /createVoiceAssetFromRecord/)
  assert.match(collectorSource, /writeAssetResourcesToDirectory/)
  assert.match(collectorSource, /readCurrentProjectSpaceState/)
  assert.match(collectorSource, /persistCurrentProjectSpaceState/)
  assert.doesNotMatch(collectorSource, /writeCurrentProjectSpaceState/)
  assert.match(collectorSource, /getPersonalSpaceDirectoryHandle/)
  assert.match(collectorSource, /personalSpaceDirectoryRequiredMessage/)
  assert.doesNotMatch(collectorSource, /archiveAssetForStorageDirectory/)
  assert.match(collectorSource, /assignAssetToCharacterColumn/)
  assert.match(collectorSource, /linkEffectAssetToVoice/)
  assert.match(collectorSource, /assignVoiceToStoryboardGroup/)
  assert.doesNotMatch(source, /星标/)
  assert.doesNotMatch(source, /StarOutlined/)
  assert.doesNotMatch(source, /StarFilled/)
  assert.doesNotMatch(source, /favoriteRecords/)
  assert.doesNotMatch(source, /toggleRecordFavorite/)
  assert.doesNotMatch(source, /onToggleFavorite/)
  assert.doesNotMatch(source, /type="primary" ghost onClick=\{\(\) => onCollect\(record\)\}/)
})

test('voice library can clear history and preview personal space voices with linked names', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const workspaceHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentWorkspace.ts', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceLibraryPanel.tsx', 'utf8')
  const listSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceRecordLists.tsx', 'utf8')
  const recordLibrarySource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceRecordLibrary.ts', 'utf8')

  assert.match(workspaceHookSource, /clearRecords/)
  assert.match(recordLibrarySource, /clearRecords/)
  assert.match(panelSource, /清空历史/)
  assert.match(panelSource, /onClearHistory/)
  assert.match(listSource, /ProjectSpaceAudioPlayer/)
  assert.match(listSource, /\{\.\.\.projectResourceReadOptions\}/)
  assert.match(listSource, /角色：/)
  assert.match(listSource, /剧情：/)
  assert.match(listSource, /linkedCharacterIds/)
  assert.match(listSource, /linkedStoryboardIds/)
  assert.doesNotMatch(listSource, /const audioSource = asset\.resourcePaths\[0\]/)
  assert.doesNotMatch(listSource, /asset\.resourcePaths\.join/)
  assert.doesNotMatch(listSource, /未绑定本地文件/)
})

test('voice generation panel exposes a searchable character picker for record prefixes', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const workspaceHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentWorkspace.ts', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceProjectSpaceActions.ts', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceGenerationPanel.tsx', 'utf8')
  const selectorSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceCharacterSelector.tsx', 'utf8')
  const workflowSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceGenerationWorkflow.ts', 'utf8')

  assert.match(workspaceHookSource, /selectedVoiceCharacterId/)
  assert.match(workspaceHookSource, /selectedVoiceCharacterName/)
  assert.match(hookSource, /addCharacterProfile/)
  assert.match(hookSource, /persistCurrentProjectSpaceState/)
  assert.doesNotMatch(source, /writeCurrentProjectSpaceState/)
  assert.match(panelSource, /from '\.\/VoiceCharacterSelector'/)
  assert.match(panelSource, /<VoiceCharacterSelector/)
  assert.match(selectorSource, /voice-character-selector/)
  assert.match(selectorSource, /搜索角色/)
  assert.match(selectorSource, /快捷创建角色/)
  assert.match(panelSource, /selectedCharacterId/)
  assert.match(panelSource, /onCharacterSelect/)
  assert.match(panelSource, /onCharacterCreate/)
  assert.doesNotMatch(panelSource, /前缀：/)
  assert.doesNotMatch(panelSource, /未选择角色前缀/)
  assert.match(workflowSource, /selectedCharacterName/)
  assert.match(workflowSource, /createVoiceRecordName\(paramsForRequest, recordCount \+ 1, selectedCharacterName\)/)
})
