import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const appSource = () => readFileSync('src/App.tsx', 'utf8')
const viteConfigSource = () => readFileSync('vite.config.ts', 'utf8')
const indexHtmlSource = () => readFileSync('index.html', 'utf8')
const siteFooterSource = () => readFileSync('src/components/SiteFooter.tsx', 'utf8')
const openSourceSoftwareSource = () => readFileSync('src/openSourceSoftware.ts', 'utf8')
const packageJsonSource = () => readFileSync('package.json', 'utf8')
const appToastProviderSource = () => readFileSync('src/components/AppToastProvider.tsx', 'utf8')

test('home page shows tool details directly instead of hiding them in a popover', () => {
  const source = appSource()

  assert.doesNotMatch(source, /Popover/)
  assert.match(source, /tool\.details/)
  assert.match(source, /tool\.shortcut/)
  assert.match(source, /tool\.output/)
})

test('home page exposes renamed workspaces and global personal space', () => {
  const source = [
    appSource(),
    readFileSync('src/components/MultiFrameSpriteWorkspace/WorkspaceShell.tsx', 'utf8'),
    readFileSync('src/components/ImageProcessingWorkspace/index.tsx', 'utf8'),
    readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8'),
  ].join('\n')

  assert.match(source, /精灵图工作台/)
  assert.match(source, /图片处理工作台/)
  assert.match(source, /配音工作台/)
  assert.match(source, /个人空间/)
  assert.doesNotMatch(source, /多图动作精灵工作台/)
  assert.doesNotMatch(source, /游戏角色语音工作台/)
})

test('home page exposes image processing workspace as a first-class tool', () => {
  const source = appSource()

  assert.match(source, /const ImageProcessingWorkspace = lazy\(\(\) => import\('\.\/components\/ImageProcessingWorkspace'\)\)/)
  assert.match(source, /type ToolId = 'multi-frame-sprite' \| 'image-processing' \| 'voice-deployment'/)
  assert.match(source, /图片处理工作台/)
  assert.match(source, /单张图片上传、色键抠图、裁剪预览并导出常用图片格式。/)
  assert.match(source, /activeSurface === 'image-processing'\s*\?\s*<ImageProcessingWorkspace \/>/)
  assert.match(source, /const personalSpaceShortcut = '4'/)
})

test('image processing workspace keeps crop result stage on the right and controls on the left', () => {
  const source = readFileSync('src/components/ImageProcessingWorkspace/index.tsx', 'utf8')
  const sideStart = source.indexOf('<div className="image-processing-side">')
  const mainStart = source.indexOf('<div className="image-processing-main">')
  const sideSource = source.slice(sideStart, mainStart)
  const mainSource = source.slice(mainStart)

  assert.notEqual(sideStart, -1)
  assert.notEqual(mainStart, -1)
  assert.match(sideSource, /<ImageUploadPanel workspace=\{workspace\} \/>[\s\S]*<ImageMattePanel workspace=\{workspace\} \/>[\s\S]*<ImageCropPanel workspace=\{workspace\} \/>[\s\S]*<ImageExportPanel workspace=\{workspace\} \/>/)
  assert.match(mainSource, /<ImageCropResultStage workspace=\{workspace\} \/>/)
  assert.doesNotMatch(mainSource, /<ImageCropPanel workspace=\{workspace\} \/>/)
  assert.doesNotMatch(sideSource, /<ImageCropResultStage workspace=\{workspace\} \/>/)
})

test('personal space is global navigation instead of a tool list item', () => {
  const source = appSource()

  assert.match(source, /type ToolId = 'multi-frame-sprite' \| 'image-processing' \| 'voice-deployment'/)
  assert.match(source, /type ActiveSurface = ToolId \| 'personal-space'/)
  assert.doesNotMatch(source, /id: 'personal-space'/)
  assert.match(source, /打开个人空间/)
  assert.match(source, /全局空间/)
  assert.match(source, /personalSpaceShortcut/)
  assert.match(source, /event\.key === personalSpaceShortcut/)
  assert.match(source, /<kbd>\{personalSpaceShortcut\}<\/kbd>/)
})

test('site footer is app-only and does not load web telemetry or filing content', () => {
  const source = siteFooterSource()
  const html = indexHtmlSource()

  assert.doesNotMatch(html, /busuanzi/i)
  assert.doesNotMatch(source, /busuanzi/i)
  assert.doesNotMatch(source, /使用人数/)
  assert.doesNotMatch(source, /浙ICP备/)
})

test('site footer exposes an about dialog with the project open source software list', () => {
  const source = appSource()
  const footerSource = siteFooterSource()
  const softwareSource = openSourceSoftwareSource()

  assert.match(source, /from '\.\/components\/SiteFooter'/)
  assert.doesNotMatch(source, /function SiteFooter/)
  assert.match(footerSource, /关于/)
  assert.match(footerSource, /GithubOutlined/)
  assert.match(footerSource, /https:\/\/github\.com\/jiawen-afk\/game-design-tools/)
  assert.match(footerSource, /target="_blank"/)
  assert.match(footerSource, /rel="noreferrer"/)
  assert.match(footerSource, /<Modal/)
  assert.match(footerSource, /openSourceSoftware/)
  assert.match(footerSource, /open-source-list/)
  assert.match(softwareSource, /export const openSourceSoftware/)
  for (const name of ['React', 'React DOM', 'Vite', 'TypeScript', 'Ant Design', 'Ant Design Icons', 'JSZip', 'tsx', 'Electron', 'Electron Builder', 'VoxCPM', 'Gradio']) {
    assert.match(softwareSource, new RegExp(name))
  }
  assert.doesNotMatch(softwareSource, /Busuanzi/)
  assert.match(softwareSource, /https:\/\/github\.com\/OpenBMB\/VoxCPM/)
})

test('personal space page covers required management modules', () => {
  const source = [
    readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalCharacterPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalResourceSections.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceFilterControl.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceTextPopover.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalSettingsPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalStoryboardPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8'),
  ].join('\n')

  assert.doesNotMatch(source, /\bList\b/)
  assert.match(source, /label: '角色'/)
  assert.match(source, /label: '剧情编排'/)
  assert.doesNotMatch(source, /label: '角色与剧情编排'/)
  assert.match(source, /label: '素材'/)
  assert.match(source, /label: '公共图片'/)
  assert.match(source, /label: '精灵图'/)
  assert.match(source, /label: '配音'/)
  assert.match(source, /title: '公共图片'/)
  assert.match(source, /title: '精灵图'/)
  assert.match(source, /title: '配音'/)
  assert.doesNotMatch(source, /label: '图片'/)
  assert.doesNotMatch(source, /title: '地图素材'/)
  assert.doesNotMatch(source, /title: '特效素材'/)
  assert.doesNotMatch(source, /label: '图片素材'/)
  assert.doesNotMatch(source, /label: '配音素材'/)
  assert.match(source, /key: 'materials'/)
  assert.doesNotMatch(source, /label: '角色管理'/)
  assert.doesNotMatch(source, /label: '剧情编排管理'/)
  assert.doesNotMatch(source, /label: '通用资源管理'/)
  assert.match(source, /设置/)
  assert.match(source, /资源存储目录/)
  assert.match(source, /删除内容同时删除资源/)
  assert.match(source, /activeKey=\{workspace\.activeModule\}/)
  assert.match(source, /onChange=\{workspace\.changeActiveModule\}/)
  assert.match(source, /disabled: !workspace\.directoryHandle/)
  assert.match(source, /directoryHandleChecked/)
  assert.match(source, /需要授权资源目录/)
  assert.match(source, /请先选择授权目录/)
  assert.match(source, /角色肖像/)
  assert.match(source, /上传肖像/)
  assert.match(source, /选择授权目录/)
  assert.match(source, /角色精灵图/)
  assert.match(source, /getSpriteUploadProps/)
  assert.match(source, /spriteUploadProps/)
  assert.match(source, /上传精灵图/)
  assert.match(source, /png 和 index\.json/)
  assert.match(source, /角色配音/)
  assert.match(source, /关联配音素材/)
  assert.match(source, /导入公共图片/)
  assert.match(source, /导入精灵图/)
  assert.match(source, /导入配音/)
  assert.match(source, /创建分组/)
  assert.match(source, /转移资产/)
  assert.match(source, /删除分组/)
  assert.match(source, /至少保留一个分组/)
  assert.match(source, /仅星标/)
  assert.match(source, /StarOutlined/)
  assert.match(source, /StarFilled/)
  assert.match(source, /toggleCharacterStar/)
  assert.match(source, /toggleStoryboardStar/)
  assert.match(source, /toggleAssetGroupStar/)
  assert.doesNotMatch(source, /<strong>角色列表<\/strong>/)
  assert.doesNotMatch(source, /<span className="section-caption">角色列表<\/span>/)
  assert.doesNotMatch(source, /<strong>剧情分组<\/strong>/)
  assert.doesNotMatch(source, /<span className="section-caption">剧情分组<\/span>/)
  assert.doesNotMatch(source, /<h3 id=\{`resource-\$\{section\.kind\}-title`\}>\{section\.title\}<\/h3>/)
  assert.doesNotMatch(source, /导出参考资产/)
  assert.match(source, /导出分组配音资产/)
  assert.match(source, /导出分组关联角色资产/)
  assert.match(source, /关联角色/)
  assert.match(source, /关联剧情组/)
  assert.match(source, /剧情顺序/)
  assert.match(source, /对白文本/)
  assert.match(source, /存储目标/)
  assert.doesNotMatch(source, /待删除资源路径/)
  assert.match(source, /personal-overview/)
  assert.doesNotMatch(source, /moduleCards/)
  assert.doesNotMatch(source, /module-map/)
})

test('matte task groups can export group images and collect them to public image assets', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/MultiFrameSpriteWorkspace/MatteWorkspacePanel.tsx', 'utf8')
  const hookSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useMattePipeline.ts', 'utf8')

  assert.match(panelSource, /导出组图片/)
  assert.match(panelSource, /收藏到个人空间/)
  assert.match(panelSource, /personalSpaceCollectEnabled/)
  assert.match(panelSource, /personalSpaceCollectDisabledReason/)
  assert.match(panelSource, /disabled=\{!personalSpaceCollectEnabled\}/)
  assert.match(panelSource, /应用到组所有帧/)
  assert.doesNotMatch(panelSource, /确定应用到该组所有帧/)
  assert.doesNotMatch(panelSource, /导出抠图/)
  assert.doesNotMatch(panelSource, /导入到个人空间/)
  assert.match(panelSource, /onExportMatteGroup/)
  assert.match(panelSource, /onImportMatteGroupToPersonalSpace/)
  assert.match(hookSource, /exportMatteGroup/)
  assert.match(hookSource, /importMatteGroupToPersonalSpace/)
  assert.match(hookSource, /个人空间-素材-公共图片/)
  assert.match(hookSource, /JSZip/)
  assert.match(hookSource, /writePersonalSpaceState/)
  assert.match(hookSource, /createResourceAssetFromUpload/)
  assert.match(source, /workspace\.matte\.exportMatteGroup/)
  assert.match(source, /workspace\.matte\.importMatteGroupToPersonalSpace/)
  assert.match(source, /workspace\.personalSpaceCollectEnabled/)
  assert.match(hookSource, /personalSpaceDirectoryRequiredMessage/)
  assert.doesNotMatch(hookSource, /importMatteGroupToPersonalSpace[\s\S]*archiveAssetForStorageDirectory/)
})

test('desktop shortcuts open tools and ignore editable targets', () => {
  const source = appSource()

  assert.match(source, /isEditableShortcutTarget/)
  assert.match(source, /event\.key === tool\.shortcut/)
  assert.match(source, /event\.key === 'Escape'/)
  assert.match(source, /HTMLInputElement/)
  assert.match(source, /HTMLTextAreaElement/)
  assert.match(source, /isContentEditable/)
})

test('production build publishes only Windows desktop deployment scripts under /scripts', () => {
  const source = viteConfigSource()

  assert.match(source, /copyDeploymentScripts/)
  assert.match(source, /dist\/scripts/)
  assert.match(source, /deploy-voxcpm\.ps1/)
  assert.doesNotMatch(source, /deploy-voxcpm\.sh/)
})

test('production build uses relative asset paths for Electron file loading', () => {
  const source = viteConfigSource()

  assert.match(source, /base:\s*'\.\/'/)
})

test('Windows desktop package uses Electron with x64 installer and portable targets', () => {
  const pkg = JSON.parse(packageJsonSource())

  assert.equal(pkg.main, 'electron/main.cjs')
  assert.equal(pkg.scripts.dev, undefined)
  assert.equal(pkg.scripts.preview, undefined)
  assert.match(pkg.scripts['desktop:build:win'], /npm run build/)
  assert.match(pkg.scripts['desktop:build:win'], /electron-builder --win --x64/)
  assert.ok(pkg.devDependencies.electron)
  assert.ok(pkg.devDependencies['electron-builder'])
  assert.equal(pkg.build.appId, 'com.linjiawen.game-design-tools')
  assert.deepEqual(pkg.build.win.target.map((target: { target: string }) => target.target), ['nsis', 'portable', 'zip'])
  assert.match(pkg.build.artifactName, /\$\{arch\}/)
})

test('Electron shell exposes a hardened desktop bridge for local system features', () => {
  const mainSource = readFileSync('electron/main.cjs', 'utf8')
  const preloadSource = readFileSync('electron/preload.cjs', 'utf8')

  assert.match(mainSource, /contextIsolation:\s*true/)
  assert.match(mainSource, /nodeIntegration:\s*false/)
  assert.match(mainSource, /preload:/)
  assert.match(mainSource, /dialog\.showOpenDialog/)
  assert.match(mainSource, /nvidia-smi/)
  assert.match(mainSource, /deploy-voxcpm\.ps1/)
  assert.match(mainSource, /voxcpm-service\.ps1/)
  assert.match(mainSource, /shell\.openPath/)
  assert.doesNotMatch(preloadSource, /ipcRenderer\s*,/)
  for (const apiName of [
    'selectPersonalSpaceDirectory',
    'readPersonalSpaceFile',
    'writePersonalSpaceFile',
    'removePersonalSpaceEntry',
    'saveFile',
    'openPath',
    'detectHardware',
    'runVoxcpmSetup',
    'queryVoxcpmSetupStatus',
    'controlVoxcpmService',
  ]) {
    assert.match(preloadSource, new RegExp(apiName))
  }
})

test('desktop bridge is integrated into personal space and VoxCPM setup workflows', () => {
  const desktopApiSource = readFileSync('src/desktopApi.ts', 'utf8')
  const storageSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceFileStorage.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceResourceActions.ts', 'utf8')
  const settingsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')
  const setupHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')
  const panelsSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')

  assert.match(desktopApiSource, /gameDesignToolsDesktop/)
  assert.match(storageSource, /createNativePersonalSpaceDirectoryHandle/)
  assert.match(storageSource, /desktop-native-directory/)
  assert.match(actionsSource, /selectPersonalSpaceDirectory/)
  assert.match(actionsSource, /saveFile/)
  assert.match(settingsHookSource, /openPath/)
  assert.match(setupHookSource, /detectHardware/)
  assert.match(setupHookSource, /runVoxcpmSetup/)
  assert.match(setupHookSource, /queryVoxcpmSetupStatus/)
  assert.match(setupHookSource, /controlVoxcpmService/)
  assert.match(panelsSource, /桌面增强/)
  assert.match(panelsSource, /检测本机配置/)
  assert.match(panelsSource, /安装依赖/)
  assert.match(panelsSource, /依赖安装查询/)
})

test('VoxCPM setup dependency query checks local installation artifacts', () => {
  const mainSource = readFileSync('electron/main.cjs', 'utf8')
  const desktopApiSource = readFileSync('src/desktopApi.ts', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')

  assert.match(mainSource, /voxcpm:setup-status/)
  assert.match(mainSource, /voxcpm-config\.json/)
  assert.match(mainSource, /replace\(\s*\/\^\\uFEFF\//)
  assert.match(mainSource, /PythonCommand/)
  assert.match(mainSource, /RepoDir/)
  assert.match(mainSource, /import voxcpm/)
  assert.match(mainSource, /import torch/)
  assert.match(mainSource, /config\.PythonArgs/)
  assert.match(mainSource, /VoxCPM 依赖已安装/)
  assert.match(mainSource, /尚未完成 VoxCPM 依赖安装/)
  assert.match(desktopApiSource, /queryVoxcpmSetupStatus/)
  assert.match(hookSource, /desktopDependencyStatusBusy/)
  assert.match(hookSource, /desktopDependencyStatusResult/)
  assert.match(hookSource, /queryDesktopDependencyStatus/)
  assert.match(panelSource, /desktopDependencyStatusResult/)
  assert.match(panelSource, /onQueryDesktopDependencyStatus/)
})

test('app-only branch removes web deployment surfaces and browser-only fallbacks', () => {
  const pkg = JSON.parse(packageJsonSource())
  const voiceModelSource = readFileSync('src/components/VoiceDeploymentWorkspace/voiceDeploymentModel.ts', 'utf8')
  const personalStorageSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceFileStorage.ts', 'utf8')
  const personalActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceResourceActions.ts', 'utf8')
  const spriteExportSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useSpriteExport.ts', 'utf8')
  const mattePipelineSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useMattePipeline.ts', 'utf8')
  const settingsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')
  const appOnlySources = [
    indexHtmlSource(),
    siteFooterSource(),
    openSourceSoftwareSource(),
    viteConfigSource(),
    voiceModelSource,
    personalStorageSource,
    personalActionsSource,
    spriteExportSource,
    mattePipelineSource,
    settingsHookSource,
  ].join('\n')

  assert.equal(pkg.scripts.preview, undefined)
  assert.equal(pkg.scripts.dev, undefined)
  for (const removedPath of ['Dockerfile', 'docker-compose.yml', 'DOCKER.md', 'docs/voxcpm-docker-deploy.md', 'scripts/deploy-voxcpm.sh']) {
    assert.equal(existsSync(removedPath), false)
  }
  for (const pattern of [
    /showDirectoryPicker/,
    /indexedDB/,
    /document\.createElement\('a'\)/,
    /window\.open/,
    /tools\.linjiawen\.com/,
    /curl -fsSL/,
    /\birm\b/,
    /Busuanzi/i,
  ]) {
    assert.doesNotMatch(appOnlySources, pattern)
  }
})

test('Ant Design alerts use v6 title prop instead of deprecated message prop', () => {
  const source = [
    readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8'),
    readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8'),
  ].join('\n')

  assert.doesNotMatch(source, /<Alert[^>]*\bmessage=/)
})

test('app shell exposes a reusable expiring toast layer', () => {
  const mainSource = readFileSync('src/main.tsx', 'utf8')
  const toastSource = appToastProviderSource()
  const appStyles = readFileSync('src/styles/app.css', 'utf8')

  assert.match(mainSource, /AppToastProvider/)
  assert.match(mainSource, /<AppToastProvider>[\s\S]*<App \/>[\s\S]*<\/AppToastProvider>/)
  assert.match(toastSource, /createContext/)
  assert.match(toastSource, /useAppToast/)
  assert.match(toastSource, /durationMs/)
  assert.match(toastSource, /expiresAt/)
  assert.match(toastSource, /remainingMs/)
  assert.match(toastSource, /onMouseEnter=\{\(\) => pauseToast\(toast\.id\)\}/)
  assert.match(toastSource, /onMouseLeave=\{\(\) => resumeToast\(toast\.id\)\}/)
  assert.match(toastSource, /window\.setTimeout/)
  assert.match(toastSource, /role="status"/)
  assert.match(toastSource, /aria-live="polite"/)
  assert.match(appStyles, /\.app-toast-viewport/)
  assert.match(appStyles, /right:\s*18px/)
  assert.match(appStyles, /bottom:\s*18px/)
  assert.match(appStyles, /@keyframes app-toast-in/)
  assert.match(appStyles, /translateY\(18px\)/)
  assert.match(appStyles, /prefers-reduced-motion:\s*reduce/)
})

test('voice deployment workspace delegates service, record, and personal space side effects', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const serviceSource = readFileSync('src/components/VoiceDeploymentWorkspace/voiceDeploymentService.ts', 'utf8')
  const setupHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')
  const generationHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceGenerationWorkflow.ts', 'utf8')

  assert.doesNotMatch(source, /from '\.\/voiceDeploymentService'/)
  assert.match(source, /from '\.\/voiceRecordStorage'/)
  assert.match(source, /from '\.\/voicePersonalSpaceCollector'/)
  assert.match(source, /useVoiceGenerationWorkflow/)
  assert.match(source, /collectVoiceRecordToPersonalSpace/)
  assert.match(setupHookSource, /from '\.\/voiceDeploymentService'/)
  assert.match(setupHookSource, /checkConnection/)
  assert.match(generationHookSource, /generateVoiceAudio/)
  assert.doesNotMatch(source, /function checkConnection/)
  assert.doesNotMatch(source, /function uploadReferenceAudio/)
  assert.doesNotMatch(source, /function readStoredRecords/)
  assert.doesNotMatch(source, /function writeStoredRecords/)
  assert.doesNotMatch(source, /function readVoiceRecordBlob/)
  assert.doesNotMatch(source, /fetch\(`\$\{serviceUrl\}\/gradio_api\/call\/generate/)
  assert.doesNotMatch(source, /readGradioEventResult/)
  assert.doesNotMatch(source, /normalizeAudioResult/)
  assert.doesNotMatch(source, /writeAssetResourcesToDirectory/)
  assert.doesNotMatch(source, /getPersonalSpaceDirectoryHandle/)
  assert.match(serviceSource, /export async function generateVoiceAudio/)
  assert.match(serviceSource, /fetch\(`\$\{serviceUrl\}\/gradio_api\/call\/generate/)
  assert.match(serviceSource, /readGradioEventResult/)
  assert.match(serviceSource, /normalizeAudioResult/)
})

test('voice deployment workspace delegates record library view components', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const listSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceRecordLists.tsx', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceLibraryPanel.tsx', 'utf8')

  assert.doesNotMatch(source, /from '\.\/VoiceRecordLists'/)
  assert.match(source, /from '\.\/VoiceLibraryPanel'/)
  assert.match(source, /<VoiceLibraryPanel/)
  assert.doesNotMatch(source, /const libraryPanel = \(/)
  assert.doesNotMatch(source, /<VoiceRecordList/)
  assert.doesNotMatch(source, /<PersonalSpaceVoiceAssetList/)
  assert.doesNotMatch(source, /function VoiceRecordList/)
  assert.doesNotMatch(source, /function PersonalSpaceVoiceAssetList/)
  assert.match(panelSource, /function VoiceLibraryPanel/)
  assert.match(panelSource, /VoiceRecordList/)
  assert.match(panelSource, /PersonalSpaceVoiceAssetList/)
  assert.match(panelSource, /label: `历史 \$\{records\.length\}`/)
  assert.match(panelSource, /label: `个人空间 \$\{personalSpaceVoiceAssets\.length\}`/)
  assert.match(listSource, /interface VoiceRecordListProps/)
  assert.match(listSource, /function VoiceRecordList/)
  assert.match(listSource, /function PersonalSpaceVoiceAssetList/)
  assert.doesNotMatch(listSource, /Dropdown\.Button/)
  assert.match(listSource, /menu=\{\{[\s\S]*收藏并关联角色/)
  assert.match(listSource, /收藏到个人空间/)
  assert.match(listSource, /personalSpaceCollectEnabled/)
  assert.match(listSource, /personalSpaceCollectDisabledReason/)
  assert.match(listSource, /disabled=\{!personalSpaceCollectEnabled\}/)
  assert.match(panelSource, /personalSpaceCollectEnabled/)
  assert.match(listSource, /收藏并关联角色/)
})

test('voice deployment workspace delegates disconnected setup panels', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const panelsSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')

  assert.match(source, /from '\.\/VoiceSetupPanels'/)
  assert.match(source, /<VoiceSetupPanels/)
  assert.doesNotMatch(source, /id="hw-title"/)
  assert.doesNotMatch(source, /id="deploy-title"/)
  assert.doesNotMatch(source, /gpuCheckCommand/)
  assert.doesNotMatch(source, /latencyDisclaimer/)
  assert.match(panelsSource, /function VoiceSetupPanels/)
  assert.doesNotMatch(panelsSource, /id="hw-title"/)
  assert.doesNotMatch(panelsSource, /环境检测/)
  assert.doesNotMatch(panelsSource, /deviceOptions/)
  assert.doesNotMatch(panelsSource, /gpuCheckCommand/)
  assert.doesNotMatch(panelsSource, /onDeviceTypeChange/)
  assert.doesNotMatch(panelsSource, /onGpuInputChange/)
  assert.match(panelsSource, /id="deploy-title"/)
  assert.match(panelsSource, /latencyDisclaimer/)
  assert.match(panelsSource, /modelOptions/)
  assert.doesNotMatch(panelsSource, /disabledPlatformValues/)
  assert.match(panelsSource, /disabledModelIds/)
  assert.doesNotMatch(panelsSource, /macOS \/ Linux/)
  assert.doesNotMatch(panelsSource, /oneClickCommand/)
  assert.doesNotMatch(panelsSource, /复制命令/)
  assert.match(panelsSource, /VoxCPM1\.5 · 约/)
  assert.match(panelsSource, /VoxCPM-0\.5B · 约/)
  assert.match(panelsSource, /sourceOptions/)
})

test('voice deployment workspace delegates connected generation panel', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceGenerationPanel.tsx', 'utf8')

  assert.match(source, /from '\.\/VoiceGenerationPanel'/)
  assert.match(source, /<VoiceGenerationPanel/)
  assert.doesNotMatch(source, /quickDesignPrompts/)
  assert.doesNotMatch(source, /生成方式/)
  assert.doesNotMatch(source, /高级控制/)
  assert.doesNotMatch(source, /参考音频文本/)
  assert.match(panelSource, /function VoiceGenerationPanel/)
  assert.match(panelSource, /quickDesignPrompts/)
  assert.match(panelSource, /生成方式/)
  assert.match(panelSource, /台词文本/)
  assert.match(panelSource, /参考音频/)
  assert.match(panelSource, /高级控制/)
  assert.match(panelSource, /onGenerate/)
  assert.match(panelSource, /onResetParams/)
  assert.doesNotMatch(panelSource, /onCopyApiExample/)
  assert.doesNotMatch(panelSource, /复制 Python 示例/)
})

test('voice deployment view keeps service controls in the top check action group', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')

  assert.match(source, /connected \? \(/)
  assert.match(source, /<Button\.Group className="voice-service-actions">/)
  assert.match(source, /重新检测[\s\S]*重启服务[\s\S]*启动服务[\s\S]*停止服务/)
  assert.match(source, /重启服务/)
  assert.match(source, /启动服务/)
  assert.match(source, /停止服务/)
  assert.match(source, /controlDesktopService\('restart'\)/)
  assert.match(source, /startDesktopService\(\)/)
  assert.doesNotMatch(source, /controlDesktopService\('start'\)\.then\(\(\) => runCheck\(port\)\)/)
  assert.match(source, /controlDesktopService\('stop'\)/)
  assert.match(source, /desktopServiceBusy/)
  assert.match(source, /desktopRuntime/)
  assert.doesNotMatch(panelSource, />\s*启动服务\s*</)
  assert.doesNotMatch(panelSource, />\s*停止服务\s*</)
  assert.doesNotMatch(panelSource, /查询状态/)
  assert.doesNotMatch(panelSource, /onControlDesktopService/)
})

test('voice deployment service command results use the shared toast layer', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')

  assert.match(source, /useAppToast/)
  assert.match(source, /showToast/)
  assert.match(source, /desktopServiceResult/)
  assert.match(source, /服务命令已执行/)
  assert.doesNotMatch(source, /className="status-alert"/)
  assert.doesNotMatch(source, /<Alert[\s\S]*desktopServiceResult/)
})

test('VoxCPM dependency setup reports visible results and validates its install script', () => {
  const mainSource = readFileSync('electron/main.cjs', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')

  assert.match(mainSource, /fs\.existsSync\(scriptPath\)/)
  assert.match(mainSource, /VoxCPM 安装脚本不存在/)
  assert.match(mainSource, /cmd\.exe/)
  assert.match(mainSource, /start/)
  assert.match(hookSource, /desktopSetupResult/)
  assert.match(hookSource, /desktopSetupError/)
  assert.match(hookSource, /setDesktopSetupResult\(result\)/)
  assert.match(hookSource, /setDesktopSetupError/)
  assert.match(panelSource, /desktopSetupResult/)
  assert.match(panelSource, /desktopSetupError/)
  assert.match(panelSource, /安装终端已打开/)
  assert.match(panelSource, /安装依赖启动失败/)
})

test('voice deployment workspace delegates collect-link dialog state', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceCollectLinkDialog.ts', 'utf8')

  assert.match(source, /from '\.\/useVoiceCollectLinkDialog'/)
  assert.match(source, /useVoiceCollectLinkDialog/)
  assert.doesNotMatch(source, /interface PendingVoiceCollectLink/)
  assert.doesNotMatch(source, /setPendingCollectLink/)
  assert.doesNotMatch(source, /const collectLinkMeta = /)
  assert.match(hookSource, /interface PendingVoiceCollectLink/)
  assert.match(hookSource, /setPendingCollectLink/)
  assert.match(hookSource, /collectLinkMeta/)
  assert.match(hookSource, /openCollectLinkDialog/)
  assert.match(hookSource, /confirmCollectLink/)
})

test('voice deployment workspace delegates generation request workflow', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceGenerationWorkflow.ts', 'utf8')

  assert.match(source, /from '\.\/useVoiceGenerationWorkflow'/)
  assert.match(source, /useVoiceGenerationWorkflow/)
  assert.doesNotMatch(source, /pendingReferenceFile/)
  assert.doesNotMatch(source, /setGenerating/)
  assert.doesNotMatch(source, /setGenerationError/)
  assert.doesNotMatch(source, /const generateVoice = async/)
  assert.doesNotMatch(source, /uploadReferenceAudio/)
  assert.match(hookSource, /pendingReferenceFile/)
  assert.match(hookSource, /setGenerating/)
  assert.match(hookSource, /setGenerationError/)
  assert.match(hookSource, /generateVoice/)
  assert.match(hookSource, /uploadReferenceAudio/)
  assert.match(hookSource, /generateVoiceAudio/)
})

test('voice deployment workspace delegates deployment setup state to a focused hook', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')

  assert.match(source, /from '\.\/useVoiceDeploymentSetup'/)
  assert.match(source, /useVoiceDeploymentSetup/)
  assert.doesNotMatch(source, /checkRef/)
  assert.doesNotMatch(source, /const runCheck = /)
  assert.doesNotMatch(source, /const applyPort = /)
  assert.doesNotMatch(source, /const hardwareReport = /)
  assert.doesNotMatch(source, /const oneClickCommand = /)
  assert.doesNotMatch(source, /const apiCallExample = /)
  assert.doesNotMatch(source, /checkConnection/)
  assert.match(hookSource, /checkRef/)
  assert.match(hookSource, /runCheck/)
  assert.match(hookSource, /applyPort/)
  assert.doesNotMatch(hookSource, /deviceType/)
  assert.doesNotMatch(hookSource, /gpuInput/)
  assert.match(hookSource, /parseNvidiaSmiReport/)
  assert.match(hookSource, /evaluateHardware/)
  assert.match(hookSource, /detectDesktopHardware/)
  assert.match(hookSource, /runDesktopSetup/)
  assert.match(hookSource, /startDesktopService/)
  assert.match(hookSource, /waitForDesktopServiceConnection/)
  assert.match(hookSource, /queryVoxcpmSetupStatus/)
  assert.match(hookSource, /依赖安装未完成/)
  assert.match(hookSource, /controlDesktopService/)
  assert.doesNotMatch(hookSource, /oneClickCommand/)
  assert.match(hookSource, /apiCallExample/)
  assert.match(hookSource, /checkConnection/)
})

test('personal space settings save gives visible feedback', () => {
  const source = [
    readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalSettingsPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8'),
  ].join('\n')

  assert.match(source, /const saveSettings = \(\) =>/)
  assert.match(source, /messageApi\.success\('已保存个人空间设置'\)/)
  assert.match(source, /savedSettings/)
  assert.match(source, /setSavedSettings\(true\)/)
  assert.match(source, /setSavedSettings\(false\)/)
  assert.match(source, /CheckCircleOutlined/)
  assert.match(source, /savedSettings \? '已保存' : '保存设置'/)
})

test('personal space workspace delegates settings panel', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSettingsPanel.tsx', 'utf8')

  assert.match(source, /from '\.\/PersonalSettingsPanel'/)
  assert.match(source, /<PersonalSettingsPanel/)
  assert.doesNotMatch(source, /<span className="field-label">资源存储目录<\/span>/)
  assert.doesNotMatch(source, /选择授权目录/)
  assert.doesNotMatch(source, /删除内容同时删除资源/)
  assert.doesNotMatch(source, /title="待删除资源路径"/)
  assert.match(panelSource, /function PersonalSettingsPanel/)
  assert.match(panelSource, /资源存储目录/)
  assert.match(panelSource, /选择授权目录/)
  assert.match(panelSource, /在文件资源管理器中打开/)
  assert.match(panelSource, /onOpenStorageDirectory/)
  assert.match(panelSource, /disabled=\{!directoryHandle\}/)
  assert.match(panelSource, /删除内容同时删除资源/)
  assert.doesNotMatch(panelSource, /待删除资源路径/)
  assert.doesNotMatch(panelSource, /pendingDeletedResourcePaths/)
  assert.match(panelSource, /onChooseStorageDirectory/)
  assert.match(panelSource, /onDeleteResourcesWithContentChange/)
})

test('personal space workspace delegates settings and directory authorization to a focused hook', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const settingsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')

  assert.match(source, /from '\.\/usePersonalSpaceSettingsWorkspace'/)
  assert.match(source, /usePersonalSpaceSettingsWorkspace/)
  assert.doesNotMatch(source, /loadPersistedPersonalSpaceDirectoryHandle/)
  assert.doesNotMatch(source, /persistPersonalSpaceDirectoryHandle/)
  assert.doesNotMatch(source, /setPersonalSpaceDirectoryHandle/)
  assert.doesNotMatch(source, /pickPersonalSpaceDirectory/)
  assert.doesNotMatch(source, /const saveSettings = /)
  assert.doesNotMatch(source, /const chooseStorageDirectory = /)
  assert.match(settingsHookSource, /loadPersistedPersonalSpaceDirectoryHandle/)
  assert.match(settingsHookSource, /persistPersonalSpaceDirectoryHandle/)
  assert.match(settingsHookSource, /setPersonalSpaceDirectoryHandle/)
  assert.match(settingsHookSource, /pickPersonalSpaceDirectory/)
  assert.match(settingsHookSource, /openStorageDirectory/)
  assert.match(settingsHookSource, /openPath/)
  assert.doesNotMatch(settingsHookSource, /window\.open/)
  assert.doesNotMatch(settingsHookSource, /file:\/\//)
  assert.match(settingsHookSource, /saveSettings/)
  assert.match(settingsHookSource, /chooseStorageDirectory/)
})

test('personal space resource kinds are first-level tabs instead of a common resource tab', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const personalSpaceCssSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpace.css', 'utf8')
  const sectionsSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalResourceSections.tsx', 'utf8')
  const previewSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalAssetPreview.tsx', 'utf8')
  const filterSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceFilterControl.tsx', 'utf8')
  const textPopoverSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceTextPopover.tsx', 'utf8')

  assert.match(hookSource, /const resourceSections/)
  assert.match(hookSource, /title: '公共图片'/)
  assert.match(hookSource, /title: '精灵图'/)
  assert.match(hookSource, /title: '配音'/)
  assert.doesNotMatch(hookSource, /title: '地图素材'/)
  assert.doesNotMatch(hookSource, /title: '特效素材'/)
  assert.match(hookSource, /assets: imageAssets/)
  assert.match(hookSource, /assets: spriteAssets/)
  assert.match(hookSource, /assets: voiceAssets/)
  assert.match(source, /label: '素材'/)
  assert.match(source, /label: '公共图片'/)
  assert.match(source, /label: '精灵图'/)
  assert.match(source, /label: '配音'/)
  assert.match(source, /workspace\.resourceSections\.filter\(\(section\) => section\.kind === 'image'\)\.map\(materialSection\)/)
  assert.match(source, /workspace\.resourceSections\.filter\(\(section\) => section\.kind === 'sprite'\)\.map\(materialSection\)/)
  assert.match(source, /workspace\.resourceSections\.filter\(\(section\) => section\.kind === 'voice'\)\.map\(materialSection\)/)
  assert.match(source, /key=\{`material-\$\{section\.kind\}`\}/)
  assert.match(source, /key: 'materials'/)
  assert.match(source, /<PersonalResourceSection/)
  assert.match(sectionsSource, /function PersonalAssetGroupControls/)
  assert.match(sectionsSource, /onAddGroup/)
  assert.match(sectionsSource, /creatingGroup/)
  assert.match(sectionsSource, /group-create-popover/)
  assert.doesNotMatch(sectionsSource, /content=\{\(\s*<div className="voice-group-rename-popover/)
  assert.match(sectionsSource, /onChangeGroupName/)
  assert.match(sectionsSource, /onDeleteGroup/)
  assert.doesNotMatch(source, /const renderResourceSection = /)
  assert.doesNotMatch(source, /section\.assets\.map/)
  assert.match(sectionsSource, /function PersonalResourceSection/)
  assert.match(sectionsSource, /from '\.\/PersonalAssetPreview'/)
  assert.match(sectionsSource, /from '\.\/PersonalSpaceFilterControl'/)
  assert.match(sectionsSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.match(sectionsSource, /<PersonalSpaceFilterControl/)
  assert.match(sectionsSource, /<PersonalSpaceTextPopover/)
  assert.match(filterSource, /export function PersonalSpaceFilterControl/)
  assert.match(filterSource, /showSearch/)
  assert.match(filterSource, /filterOption/)
  assert.match(filterSource, /筛选/)
  assert.match(filterSource, /仅星标/)
  assert.match(textPopoverSource, /export function PersonalSpaceTextPopover/)
  assert.match(textPopoverSource, /<Popover/)
  assert.match(textPopoverSource, /<Input/)
  assert.match(textPopoverSource, /onPressEnter/)
  assert.match(textPopoverSource, /voice-group-rename-popover/)
  assert.match(textPopoverSource, /确认/)
  assert.match(textPopoverSource, /取消/)
  assert.doesNotMatch(sectionsSource, /export function PersonalAssetPreview/)
  assert.doesNotMatch(sectionsSource, /readStoredResourceBlob/)
  assert.doesNotMatch(sectionsSource, /loadPersistedPersonalSpaceDirectoryHandle/)
  assert.match(previewSource, /export function PersonalAssetPreview/)
  assert.match(previewSource, /readStoredResourceBlob/)
  assert.match(previewSource, /loadPersistedPersonalSpaceDirectoryHandle/)
  assert.match(previewSource, /spriteFrameModalStyle/)
  const resourceSectionBody = sectionsSource.slice(sectionsSource.indexOf('export function PersonalResourceSection'))
  assert.match(resourceSectionBody, /const \[selectedGroup, setSelectedGroup\] = useState/)
  assert.match(resourceSectionBody, /const \[selectedAssetIdsByGroup, setSelectedAssetIdsByGroup\] = useState/)
  assert.match(resourceSectionBody, /全选/)
  assert.match(resourceSectionBody, /取消全选/)
  assert.match(resourceSectionBody, /删除选中资产/)
  assert.match(resourceSectionBody, /selectedAssetIds\.forEach\(\(assetId\) => onDeleteAsset\(assetId\)\)/)
  assert.match(resourceSectionBody, /disabled=\{selectedAssetIds\.length === 0\}/)
  assert.match(resourceSectionBody, /updateSelectedAssetIdsForGroup\(groupName, \[\]\)/)
  assert.match(resourceSectionBody, /asset-selection-checkbox/)
  assert.match(resourceSectionBody, /selectedAssetIds/)
  assert.match(resourceSectionBody, /const isVoiceSection = section\.kind === 'voice'/)
  assert.match(resourceSectionBody, /const isGroupedResourceSection = section\.kind === 'image' \|\| section\.kind === 'sprite' \|\| isVoiceSection/)
  assert.match(resourceSectionBody, /const visibleVoiceGroupNames/)
  assert.match(resourceSectionBody, /slice\(-20\)\.reverse\(\)/)
  assert.match(resourceSectionBody, /voice-group-filter/)
  assert.doesNotMatch(resourceSectionBody, /filterOption/)
  assert.match(resourceSectionBody, /最近创建的20个分组/)
  assert.match(resourceSectionBody, /voice-group-toolbar/)
  assert.match(resourceSectionBody, /voice-group-block/)
  assert.match(resourceSectionBody, /voice-group-header/)
  assert.match(resourceSectionBody, /voice-group-left-actions/)
  assert.match(resourceSectionBody, /voice-group-right-actions/)
  assert.match(resourceSectionBody, /<div className="voice-group-right-actions">[\s\S]*删除分组[\s\S]*<\/div>/)
  assert.match(resourceSectionBody, /voice-group-actions/)
  assert.match(resourceSectionBody, /voice-group-admin-actions/)
  assert.match(resourceSectionBody, /renamingGroupName/)
  assert.match(resourceSectionBody, /resource-section--voice/)
  assert.match(resourceSectionBody, /上传到分组/)
  assert.match(sectionsSource, /Dropdown/)
  assert.match(sectionsSource, /DownOutlined/)
  assert.match(sectionsSource, /转移并删除该分组/)
  assert.doesNotMatch(sectionsSource, /转移资产并删除该分组/)
  assert.match(sectionsSource, /onDeleteGroup\(kind, groupName, \{ transferToGroup: transferTo \}\)/)
  assert.match(resourceSectionBody, /onDeleteGroup=\{onDeleteGroup\}/)
  assert.match(resourceSectionBody, /onRenameGroup\(section\.kind, groupName, renameTo\)/)
  assert.match(resourceSectionBody, /onDeleteGroup\(section\.kind, groupName, \{ deleteAssets: true \}\)/)
  assert.match(sectionsSource, /selectedAssetIds\.forEach/)
  assert.match(sectionsSource, /onChangeGroupName\(assetId, transferTo\)/)
  assert.match(sectionsSource, /disabled=\{!transferTo \|\| selectedAssetIds\.length === 0\}/)
  assert.match(resourceSectionBody, /commonResourceUploadProps\(section\.kind, groupName\)/)
  assert.match(resourceSectionBody, /spriteResourceUploadProps\(groupName\)/)
  assert.match(resourceSectionBody, /isGroupedResourceSection \?/)
  assert.doesNotMatch(resourceSectionBody, /!isVoiceSection && groupAssets\.length === 0/)
  assert.match(resourceSectionBody, /value=\{selectedGroup\}/)
  assert.match(resourceSectionBody, /onChange=\{setSelectedGroup\}/)
  assert.match(resourceSectionBody, /const groupAssets = section\.assets\.filter\(\(item\) => item\.groupName === selectedGroup\)/)
  assert.match(previewSource, /preview-image/)
  assert.match(previewSource, /audioRef/)
  assert.match(previewSource, /spritePlaying/)
  assert.match(previewSource, /spriteFrameIndex/)
  assert.match(previewSource, /window\.setInterval/)
  assert.match(sectionsSource, /导入时间/)
  assert.match(sectionsSource, /groupAssets\.map/)
  assert.doesNotMatch(sectionsSource, /addonBefore="标签"/)
  assert.doesNotMatch(sectionsSource, /aria-label=\{`\$\{section\.title\}标签`\}/)
  assert.doesNotMatch(sectionsSource, /aria-label=\{`\$\{section\.title\}分组`\}/)
  assert.match(sectionsSource, /关联配音素材/)
  assert.match(sectionsSource, /关联角色/)
  assert.match(sectionsSource, /关联剧情组/)
  assert.match(sectionsSource, /voice-resource-list/)
  assert.match(sectionsSource, /voice-group-list/)
  assert.match(sectionsSource, /voice-resource-panel/)
  assert.match(sectionsSource, /voice-space-record/)
  assert.match(sectionsSource, /voice-record-fields/)
  assert.match(sectionsSource, /剧情顺序/)
  assert.match(personalSpaceCssSource, /\.voice-group-actions\s*\{[^}]*flex-wrap: nowrap;/)
  assert.match(personalSpaceCssSource, /\.voice-group-right-actions\s*\{[^}]*flex-wrap: nowrap;/)
  assert.doesNotMatch(source, /label: '图片'/)
  assert.doesNotMatch(sectionsSource, /未绑定本地文件/)
  assert.doesNotMatch(sectionsSource, /resourcePaths\.join/)
  assert.doesNotMatch(source, /key: 'assets'/)
  assert.doesNotMatch(source, /label: '通用资源管理'/)
  assert.doesNotMatch(source, /label: '地图素材'/)
  assert.doesNotMatch(source, /label: '特效素材'/)
  assert.doesNotMatch(source, /<strong>地图素材 \/ 特效素材 \/ 配音素材<\/strong>/)
  assert.doesNotMatch(source, /space\.assets\.map\(\(item\)/)
})

test('personal space workspace delegates character management panel', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const panelSource = [
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalCharacterPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/CharacterAssetPicker.tsx', 'utf8'),
  ].join('\n')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const personalSpaceCssSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpace.css', 'utf8')

  assert.match(source, /from '\.\/PersonalCharacterPanel'/)
  assert.match(source, /<PersonalCharacterPanel/)
  assert.match(panelSource, /from '\.\/CharacterAssetPicker'/)
  assert.doesNotMatch(source, /角色列表/)
  assert.doesNotMatch(source, /<strong>角色肖像<\/strong>/)
  assert.doesNotMatch(source, /<strong>角色精灵图<\/strong>/)
  assert.doesNotMatch(source, /<strong>角色配音<\/strong>/)
  assert.match(panelSource, /function PersonalCharacterPanel/)
  assert.match(panelSource, /from '\.\/PersonalSpaceFilterControl'/)
  assert.match(panelSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.match(panelSource, /<PersonalSpaceFilterControl/)
  assert.match(panelSource, /<PersonalSpaceTextPopover/)
  assert.match(panelSource, /creatingCharacter/)
  assert.match(panelSource, /character-create-popover/)
  assert.match(panelSource, /selectedCharacterFilter/)
  assert.match(panelSource, /recentCharacterOptions/)
  assert.match(panelSource, /character-panel-toolbar/)
  assert.match(panelSource, /character-filter-control/)
  assert.match(panelSource, /最近创建的20个角色/)
  assert.doesNotMatch(panelSource, /filterOption/)
  assert.match(panelSource, /renamingCharacterId/)
  assert.match(panelSource, /characterNameDrafts/)
  assert.match(panelSource, /EditOutlined/)
  assert.match(panelSource, /角色名称/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover character-create-popover/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover character-name-rename-popover/)
  assert.doesNotMatch(panelSource, /className="character-name-input"[\s\S]*onChange=\{\(event\) => onRenameCharacter/)
  assert.doesNotMatch(panelSource, /<strong>角色列表<\/strong>/)
  assert.doesNotMatch(panelSource, /<span className="section-caption">角色列表<\/span>/)
  assert.match(panelSource, /角色肖像/)
  assert.match(panelSource, /角色精灵图/)
  assert.match(panelSource, /角色配音/)
  assert.match(panelSource, /上传肖像/)
  assert.match(hookSource, /const portraitAssets = imageAssets/)
  assert.match(panelSource, /function CharacterAssetPicker/)
  assert.match(panelSource, /character-link-actions/)
  assert.match(panelSource, /关联肖像/)
  assert.match(panelSource, /portrait-picker-popover/)
  assert.match(panelSource, /selectedAssetId/)
  assert.match(panelSource, /确认关联肖像/)
  assert.match(panelSource, /确认关联精灵图/)
  assert.match(panelSource, /确认关联配音/)
  assert.doesNotMatch(panelSource, /placeholder="关联肖像资源"/)
  assert.doesNotMatch(panelSource, /placeholder="关联精灵图资源"/)
  assert.doesNotMatch(panelSource, /placeholder="关联配音资源"/)
  assert.doesNotMatch(panelSource, /角色肖像标签/)
  assert.doesNotMatch(panelSource, /角色精灵图标签/)
  assert.doesNotMatch(panelSource, /未设置标签/)
  assert.match(panelSource, /PersonalAssetPreview/)
  assert.match(panelSource, /关联备注/)
  assert.match(panelSource, /取消关联/)
  assert.match(panelSource, /DisconnectOutlined/)
  assert.match(panelSource, /onUnassignAsset/)
  assert.match(panelSource, /onMoveCharacterVoice/)
  assert.match(panelSource, /draggable/)
  assert.match(panelSource, /onDrop/)
  assert.doesNotMatch(panelSource, /onReorderCharacterVoice/)
  assert.doesNotMatch(panelSource, /角色配音标签/)
  assert.doesNotMatch(panelSource, /角色配音关联备注/)
  assert.match(panelSource, /voiceAsset\?\.dialogueText/)
  assert.match(panelSource, /aria-label="取消关联角色肖像"/)
  assert.match(panelSource, /aria-label="取消关联角色精灵图"/)
  assert.match(panelSource, /aria-label="取消关联角色配音"/)
  assert.match(personalSpaceCssSource, /\.character-panel-toolbar\s*\{[^}]*display: flex;/)
  assert.match(personalSpaceCssSource, /\.character-filter-control,\s*\.storyboard-filter-control\s*\{[^}]*display: flex;/)
})

test('personal space workspace delegates storyboard management panel', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const panelSource = [
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalStoryboardPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/StoryboardVoicePicker.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/StoryboardVoiceRow.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/StoryboardCharacterAvatar.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/storyboardPlaybackSources.ts', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/storyboardVoiceDrag.ts', 'utf8'),
  ].join('\n')
  const personalSpaceCssSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpace.css', 'utf8')

  assert.match(source, /from '\.\/PersonalStoryboardPanel'/)
  assert.match(source, /<PersonalStoryboardPanel/)
  assert.match(panelSource, /from '\.\/StoryboardVoicePicker'/)
  assert.match(panelSource, /from '\.\/StoryboardVoiceRow'/)
  assert.match(panelSource, /from '\.\/storyboardPlaybackSources'/)
  assert.match(panelSource, /from '\.\/storyboardVoiceDrag'/)
  assert.doesNotMatch(source, /剧情分组/)
  assert.doesNotMatch(source, /复制参考资产/)
  assert.doesNotMatch(source, /导出参考资产/)
  assert.doesNotMatch(source, /对白文本/)
  assert.match(panelSource, /function PersonalStoryboardPanel/)
  assert.match(panelSource, /from '\.\/PersonalSpaceFilterControl'/)
  assert.match(panelSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.match(panelSource, /<PersonalSpaceFilterControl/)
  assert.match(panelSource, /<PersonalSpaceTextPopover/)
  assert.doesNotMatch(panelSource, /<strong>剧情分组<\/strong>/)
  assert.doesNotMatch(panelSource, /<span className="section-caption">剧情分组<\/span>/)
  assert.doesNotMatch(panelSource, /复制参考资产/)
  assert.doesNotMatch(panelSource, /导出参考资产/)
  assert.match(panelSource, /导出分组配音资产/)
  assert.match(panelSource, /导出分组关联角色资产/)
  assert.match(panelSource, /导出所有分组配音资产/)
  assert.match(panelSource, /导出所有分组关联角色资产/)
  assert.match(panelSource, /storyboardExportingKey/)
  assert.match(panelSource, /creatingStoryboard/)
  assert.match(panelSource, /selectedStoryboardFilter/)
  assert.match(panelSource, /recentStoryboardOptions/)
  assert.match(panelSource, /storyboard-filter-control/)
  assert.match(panelSource, /最近创建的20个剧情组/)
  assert.match(panelSource, /visibleStoryboardGroups/)
  assert.doesNotMatch(panelSource, /filterOption/)
  assert.match(panelSource, /renamingStoryboardId/)
  assert.match(panelSource, /storyboardNameDrafts/)
  assert.match(panelSource, /EditOutlined/)
  assert.match(panelSource, /分组名称/)
  assert.doesNotMatch(panelSource, /className="storyboard-name-input"[\s\S]*onChange=\{\(event\) => onRenameStoryboard/)
  assert.match(panelSource, /storyboard-create-popover/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover storyboard-create-popover/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover storyboard-name-rename-popover/)
  assert.doesNotMatch(panelSource, /导入角色/)
  assert.match(panelSource, /关联配音/)
  assert.match(panelSource, /导入配音/)
  assert.match(panelSource, /getStoryboardVoiceUploadProps/)
  assert.match(source, /storyboardVoiceUploadProps/)
  assert.doesNotMatch(panelSource, /搜索角色/)
  assert.match(panelSource, /搜索配音/)
  assert.match(panelSource, /voice-picker-popover/)
  assert.match(panelSource, /selectedVoiceAssetIds/)
  assert.match(panelSource, /lastSelectedVoiceAssetId/)
  assert.match(panelSource, /event\.altKey/)
  assert.match(panelSource, /event\.shiftKey/)
  assert.match(panelSource, /selectedVoiceAssetIds\.forEach\(\(assetId\) => onAssignVoiceToStoryboard\(groupId, assetId\)\)/)
  assert.doesNotMatch(panelSource, /selectedVoiceAssetId,\s*setSelectedVoiceAssetId/)
  assert.match(panelSource, /<Modal/)
  assert.doesNotMatch(panelSource, /<span className="field-label">导入配音<\/span>/)
  assert.doesNotMatch(panelSource, /placeholder="选择配音素材"/)
  assert.match(panelSource, /storyboard-character-list/)
  assert.match(panelSource, /storyboard-voice-row/)
  assert.match(panelSource, /storyboard-timeline/)
  assert.match(panelSource, /从这里开始播放/)
  assert.match(panelSource, /停止播放/)
  assert.match(panelSource, /playStoryboardFrom/)
  assert.match(panelSource, /readStoredResourceBlob/)
  assert.match(panelSource, /storageResourcePaths\[0\]/)
  assert.match(panelSource, /playbackObjectUrlsRef/)
  assert.match(panelSource, /stopStoryboardPlayback/)
  assert.match(panelSource, /onEnded=\{playNextStoryboardVoice\}/)
  assert.match(panelSource, /PersonalAssetPreview/)
  assert.doesNotMatch(panelSource, /关联备注/)
  assert.doesNotMatch(panelSource, /未关联角色/)
  assert.doesNotMatch(panelSource, /UpOutlined/)
  assert.doesNotMatch(panelSource, /DownOutlined/)
  assert.match(panelSource, /onAssignStoryboardVoiceCharacter/)
  assert.match(panelSource, /draggedStoryboardVoice/)
  assert.match(panelSource, /previewStoryboardVoiceOrders/)
  assert.match(panelSource, /dropPlacement/)
  assert.match(panelSource, /storyboard-voice-row is-dragging/)
  assert.match(panelSource, /storyboard-voice-row is-drop-target/)
  assert.match(panelSource, /data-storyboard-voice-id/)
  assert.match(panelSource, /getStoryboardVoiceListDropTarget/)
  assert.match(panelSource, /previewStoryboardVoiceListDrop/)
  assert.match(panelSource, /dropStoryboardVoiceOnList/)
  assert.match(panelSource, /querySelectorAll<HTMLElement>\('\[data-storyboard-voice-id\]'\)/)
  assert.match(panelSource, /row\.assetId !== draggedAssetId/)
  assert.match(panelSource, /storyboard-voice-pane"[\s\S]*onDragOver=\{\(event\) =>/)
  assert.match(panelSource, /storyboard-voice-pane"[\s\S]*onDrop=\{\(event\) => dropStoryboardVoiceOnList\(event, item\.id\)\}/)
  assert.match(panelSource, /storyboard-voice-pane"[\s\S]*onDragLeave=\{\(event\) => cancelStoryboardVoiceListDrop\(event, item\.id\)\}/)
  assert.match(panelSource, /function cancelStoryboardVoiceListDrop/)
  assert.match(panelSource, /event\.currentTarget\.contains\(event\.relatedTarget as Node \| null\)/)
  assert.match(panelSource, /delete next\[groupId\]/)
  assert.match(personalSpaceCssSource, /\.storyboard-voice-pane\s*\{[^}]*padding:/)
  assert.match(personalSpaceCssSource, /\.storyboard-voice-pane\s*\{[^}]*min-height:/)
  assert.doesNotMatch(panelSource, /storyboard-voice-edge-drop/)
  assert.doesNotMatch(panelSource, /拖到最前/)
  assert.doesNotMatch(panelSource, /拖到最后/)
  assert.match(panelSource, /draggable/)
  assert.match(panelSource, /onDrop/)
  assert.match(panelSource, /对白文本/)
  assert.doesNotMatch(panelSource, /onReorderStoryboardVoice/)
  assert.match(panelSource, /onMoveStoryboardVoice/)
  assert.match(panelSource, /onUnassignStoryboardVoice/)
  assert.match(panelSource, /取消关联配音/)
  assert.match(panelSource, /DisconnectOutlined/)
  assert.match(panelSource, /storyboard-panel-toolbar/)
})

test('personal space workspace delegates resource IO and filesystem side effects', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const settingsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceResourceActions.ts', 'utf8')

  assert.match(hookSource, /from '\.\/personalSpaceResourceActions'/)
  assert.match(settingsHookSource, /pickPersonalSpaceDirectory/)
  assert.match(hookSource, /exportStoryboardAssetToTarget/)
  assert.match(hookSource, /createPortraitAssetForUpload/)
  assert.match(hookSource, /createCommonResourceAssetForUpload/)
  assert.match(hookSource, /deleteAssetWithOptionalResources/)
  assert.match(hookSource, /applyAssetDeleteResult/)
  assert.doesNotMatch(source, /from '\.\/personalSpaceResourceActions'/)
  assert.doesNotMatch(source, /pickPersonalSpaceDirectory/)
  assert.doesNotMatch(source, /createCommonResourceAssetForUpload/)
  assert.doesNotMatch(source, /deleteAssetWithOptionalResources/)
  assert.doesNotMatch(source, /function supportsDirectoryPicker/)
  assert.doesNotMatch(source, /function downloadJsonFile/)
  assert.doesNotMatch(source, /function pickDirectoryHandle/)
  assert.doesNotMatch(source, /URL\.createObjectURL\(file\)/)
  assert.doesNotMatch(source, /writeAssetResourcesToDirectory/)
  assert.doesNotMatch(source, /writeJsonFileToDirectory/)
  assert.doesNotMatch(source, /deleteStoredResourceFiles/)
  assert.doesNotMatch(actionsSource, /showDirectoryPicker/)
  assert.match(actionsSource, /saveFile/)
  assert.match(actionsSource, /URL\.createObjectURL/)
  assert.match(actionsSource, /JSZip/)
  assert.match(actionsSource, /storyboard\.json/)
  assert.match(actionsSource, /writeAssetResourcesToDirectory/)
  assert.match(actionsSource, /writeBlobFileToDirectory/)
  assert.match(actionsSource, /readStoredResourceBlob/)
  assert.match(actionsSource, /storageResourcePaths/)
  assert.match(actionsSource, /deleteStoredResourceFiles/)
})

test('personal space workspace delegates page state and resource workflow', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/index.tsx', 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')

  assert.match(source, /from '\.\/usePersonalSpaceWorkspace'/)
  assert.match(source, /usePersonalSpaceWorkspace/)
  assert.doesNotMatch(source, /useState/)
  assert.doesNotMatch(source, /useEffect/)
  assert.doesNotMatch(source, /readPersonalSpaceState/)
  assert.doesNotMatch(source, /writePersonalSpaceState/)
  assert.doesNotMatch(source, /pickPersonalSpaceDirectory/)
  assert.doesNotMatch(source, /createCommonResourceAssetForUpload/)
  assert.doesNotMatch(source, /deleteAssetWithOptionalResources/)
  assert.match(hookSource, /useState/)
  assert.match(hookSource, /useEffect/)
  assert.match(hookSource, /activeModule/)
  assert.match(hookSource, /setActiveModule/)
  assert.match(hookSource, /changeActiveModule/)
  assert.match(hookSource, /directoryHandleChecked/)
  assert.match(hookSource, /setActiveModule\('settings'\)/)
  assert.match(hookSource, /readPersonalSpaceState/)
  assert.match(hookSource, /writePersonalSpaceState/)
  assert.match(hookSource, /usePersonalSpaceSettingsWorkspace/)
  assert.match(hookSource, /uploadCharacterPortrait/)
  assert.match(hookSource, /uploadCommonResource/)
  assert.match(hookSource, /deleteAsset/)
  assert.match(hookSource, /resourceSections/)
})

test('personal space model delegates asset factories and storage paths', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceModel.ts', 'utf8')
  const assetSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceAssets.ts', 'utf8')

  assert.match(source, /from '\.\/personalSpaceAssets'/)
  assert.match(source, /export \{[\s\S]*createPersonalSpaceAsset[\s\S]*archiveAssetForStorageDirectory[\s\S]*createResourceAssetFromUpload[\s\S]*\} from '\.\/personalSpaceAssets'/)
  assert.doesNotMatch(source, /function sanitizePathPart/)
  assert.doesNotMatch(source, /function groupNameForUploadedResource/)
  assert.doesNotMatch(source, /export function createPersonalSpaceAsset/)
  assert.doesNotMatch(source, /export function archiveAssetForStorageDirectory/)
  assert.doesNotMatch(source, /export function createResourceAssetFromUpload/)
  assert.match(assetSource, /export function createPersonalSpaceAsset/)
  assert.match(assetSource, /export function archiveAssetForStorageDirectory/)
  assert.match(assetSource, /export function createResourceAssetFromUpload/)
  assert.match(assetSource, /function sanitizePathPart/)
  assert.match(assetSource, /function groupNameForUploadedResource/)
})

test('personal space model delegates storyboard operations', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceModel.ts', 'utf8')
  const storyboardSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceStoryboards.ts', 'utf8')

  assert.match(source, /from '\.\/personalSpaceStoryboards'/)
  assert.match(source, /export \{[\s\S]*addStoryboardGroup[\s\S]*assignVoiceToStoryboardGroup[\s\S]*exportStoryboardReference[\s\S]*\} from '\.\/personalSpaceStoryboards'/)
  assert.doesNotMatch(source, /export function addStoryboardGroup/)
  assert.doesNotMatch(source, /export function assignVoiceToStoryboardGroup/)
  assert.doesNotMatch(source, /export function exportStoryboardReference/)
  assert.match(storyboardSource, /export function addStoryboardGroup/)
  assert.match(storyboardSource, /export function assignVoiceToStoryboardGroup/)
  assert.match(storyboardSource, /export function unassignVoiceFromStoryboardGroup/)
  assert.match(storyboardSource, /export function getStoryboardLinkedCharacterIds/)
  assert.match(storyboardSource, /export function exportStoryboardReference/)
})

test('personal space model delegates state persistence and cloning', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceModel.ts', 'utf8')
  const stateSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceState.ts', 'utf8')

  assert.match(source, /from '\.\/personalSpaceState'/)
  assert.match(source, /export \{[\s\S]*clonePersonalSpaceState[\s\S]*readPersonalSpaceState[\s\S]*writePersonalSpaceState[\s\S]*\} from '\.\/personalSpaceState'/)
  assert.doesNotMatch(source, /export const defaultPersonalSpaceState/)
  assert.doesNotMatch(source, /export function clonePersonalSpaceState/)
  assert.doesNotMatch(source, /export function readPersonalSpaceState/)
  assert.doesNotMatch(source, /export function writePersonalSpaceState/)
  assert.match(stateSource, /export const defaultPersonalSpaceState/)
  assert.match(stateSource, /export function clonePersonalSpaceState/)
  assert.match(stateSource, /export function createPersonalSpaceId/)
})

test('personal space model delegates character operations', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceModel.ts', 'utf8')
  const characterSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceCharacters.ts', 'utf8')

  assert.match(source, /from '\.\/personalSpaceCharacters'/)
  assert.match(source, /export \{[\s\S]*addCharacterProfile[\s\S]*assignAssetToCharacterColumn[\s\S]*moveCharacterVoice[\s\S]*\} from '\.\/personalSpaceCharacters'/)
  assert.doesNotMatch(source, /export function addCharacterProfile/)
  assert.doesNotMatch(source, /export function assignAssetToCharacterColumn/)
  assert.doesNotMatch(source, /export function moveCharacterVoice/)
  assert.doesNotMatch(source, /function normalizeCharacterOrder/)
  assert.match(characterSource, /export function addCharacterProfile/)
  assert.match(characterSource, /export function assignAssetToCharacterColumn/)
  assert.match(characterSource, /export function unassignAssetFromCharacterColumn/)
  assert.match(characterSource, /export function moveCharacterVoice/)
  assert.match(characterSource, /function normalizeCharacterOrder/)
})

test('personal space model delegates asset update and delete operations', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceModel.ts', 'utf8')
  const operationsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceAssetOperations.ts', 'utf8')

  assert.match(source, /from '\.\/personalSpaceAssetOperations'/)
  assert.match(source, /export \{[\s\S]*deletePersonalSpaceAsset[\s\S]*updatePersonalSpaceAsset[\s\S]*\} from '\.\/personalSpaceAssetOperations'/)
  assert.doesNotMatch(source, /export function updatePersonalSpaceAsset/)
  assert.doesNotMatch(source, /export function deletePersonalSpaceAsset/)
  assert.doesNotMatch(source, /normalizeAssetLinks/)
  assert.match(operationsSource, /export function updatePersonalSpaceAsset/)
  assert.match(operationsSource, /export function deletePersonalSpaceAsset/)
  assert.match(operationsSource, /normalizeAssetLinks/)
})

test('layout workspace delegates batch frame layout presets to the model', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/useLayoutWorkspace.ts', 'utf8')
  const modelSource = readFileSync('src/components/MultiFrameSpriteWorkspace/layoutModel.ts', 'utf8')

  assert.match(source, /applyLayoutPresetToFrames/)
  assert.match(modelSource, /export function applyLayoutPresetToFrames/)
  assert.doesNotMatch(source, /const applyAllSize = /)
  assert.doesNotMatch(source, /Math\.max\(\.\.\.frames\.map\(\(f\) => f\.layout\.width\)\)/)
  assert.doesNotMatch(source, /item\.matteWidth \/ Math\.max\(1, item\.matteHeight\)/)
})

test('layout workspace delegates canvas ratio apply feedback to a focused hook', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/useLayoutWorkspace.ts', 'utf8')
  const feedbackSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useCanvasRatioApplyFeedback.ts', 'utf8')

  assert.match(source, /from '\.\/useCanvasRatioApplyFeedback'/)
  assert.match(source, /useCanvasRatioApplyFeedback/)
  assert.doesNotMatch(source, /CANVAS_RATIO_MESSAGE_KEY/)
  assert.doesNotMatch(source, /canvasRatioApplyIdsRef/)
  assert.doesNotMatch(source, /canvasRatioFallbackTimerRef/)
  assert.doesNotMatch(source, /getPendingComposedFrameIds/)
  assert.match(feedbackSource, /CANVAS_RATIO_MESSAGE_KEY/)
  assert.match(feedbackSource, /getPendingComposedFrameIds/)
  assert.match(feedbackSource, /startCanvasRatioApplyFeedback/)
  assert.match(feedbackSource, /canvasRatioApplying/)
})

test('layout workspace delegates pointer and keyboard interactions to a focused hook', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/useLayoutWorkspace.ts', 'utf8')
  const interactionSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useLayoutPointerInteractions.ts', 'utf8')

  assert.match(source, /from '\.\/useLayoutPointerInteractions'/)
  assert.match(source, /useLayoutPointerInteractions/)
  assert.doesNotMatch(source, /const onPointerMove = useCallback/)
  assert.doesNotMatch(source, /window\.addEventListener\('pointermove'/)
  assert.doesNotMatch(source, /window\.addEventListener\('keydown'/)
  assert.doesNotMatch(source, /const onKeyDown = \(e: KeyboardEvent\)/)
  assert.match(interactionSource, /window\.addEventListener\('pointermove'/)
  assert.match(interactionSource, /window\.addEventListener\('keydown'/)
  assert.match(interactionSource, /computeKeyboardOffset/)
  assert.match(interactionSource, /computeHandleResize/)
  assert.match(interactionSource, /guideDragState/)
})

test('matte pipeline delegates default parameter persistence to a focused hook', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/useMattePipeline.ts', 'utf8')
  const defaultsHook = readFileSync('src/components/MultiFrameSpriteWorkspace/useMatteDefaultsWorkspace.ts', 'utf8')

  assert.match(source, /from '\.\/useMatteDefaultsWorkspace'/)
  assert.match(source, /useMatteDefaultsWorkspace/)
  assert.doesNotMatch(source, /readStoredMatteDefaults/)
  assert.doesNotMatch(source, /writeStoredMatteDefaults/)
  assert.doesNotMatch(source, /const openMatteDefaults = /)
  assert.doesNotMatch(source, /const saveMatteDefaults = /)
  assert.match(defaultsHook, /readStoredMatteDefaults/)
  assert.match(defaultsHook, /writeStoredMatteDefaults/)
  assert.match(defaultsHook, /coerceMatteDefaults/)
  assert.match(defaultsHook, /openMatteDefaults/)
  assert.match(defaultsHook, /saveMatteDefaults/)
})

test('video workspace delegates extracted frame preview and crop interactions to a focused hook', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/useVideoWorkspace.ts', 'utf8')
  const previewSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useVideoFramePreviewWorkspace.ts', 'utf8')

  assert.match(source, /from '\.\/useVideoFramePreviewWorkspace'/)
  assert.match(source, /useVideoFramePreviewWorkspace/)
  assert.doesNotMatch(source, /ResizeObserver/)
  assert.doesNotMatch(source, /setInterval/)
  assert.doesNotMatch(source, /videoCropDrag/)
  assert.doesNotMatch(source, /getContainedImageRect/)
  assert.match(previewSource, /ResizeObserver/)
  assert.match(previewSource, /setInterval/)
  assert.match(previewSource, /videoCropDrag/)
  assert.match(previewSource, /getContainedImageRect/)
  assert.match(previewSource, /startVideoCropDrag/)
})

test('video upload panel delegates extracted frame preview controls to a focused component', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/VideoUploadPanel.tsx', 'utf8')
  const previewPanelSource = readFileSync('src/components/MultiFrameSpriteWorkspace/VideoFramePreviewPanel.tsx', 'utf8')

  assert.match(source, /from '\.\/VideoFramePreviewPanel'/)
  assert.match(source, /<VideoFramePreviewPanel/)
  assert.doesNotMatch(source, /from '\.\/VideoCropOverlay'/)
  assert.doesNotMatch(source, /from '\.\/VideoFrameList'/)
  assert.doesNotMatch(source, /video-preview-box/)
  assert.doesNotMatch(source, /video-frame-list-panel/)
  assert.doesNotMatch(source, /video-confirm-action/)
  assert.match(previewPanelSource, /VideoCropOverlay/)
  assert.match(previewPanelSource, /VideoFrameList/)
  assert.match(previewPanelSource, /video-preview-box/)
  assert.match(previewPanelSource, /video-frame-list-panel/)
  assert.match(previewPanelSource, /video-confirm-action/)
})
