import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

test('personal space resource kinds are first-level tabs instead of a common resource tab', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceWorkbench.tsx', 'utf8')
  const materialsPanelSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalMaterialsPanel.tsx', 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const derivedSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceDerivedState.ts', 'utf8')
  const personalSpaceCssSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpace.voiceGroups.css', 'utf8')
  const sectionsSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalResourceSections.tsx', 'utf8')
  const assetRecordSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalResourceAssetRecord.tsx', 'utf8')
  const groupBlockSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalResourceGroupBlock.tsx', 'utf8')
  const previewSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalAssetPreview.tsx', 'utf8')
  const filterSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceFilterControl.tsx', 'utf8')
  const textPopoverSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceTextPopover.tsx', 'utf8')
  const recentStarredFilterSource = readFileSync('src/components/PersonalSpaceWorkspace/useRecentStarredFilter.ts', 'utf8')
  const createNamePopoverHookPath = 'src/components/PersonalSpaceWorkspace/useCreateNamePopover.ts'
  const createNamePopoverHookSource = existsSync(createNamePopoverHookPath) ? readFileSync(createNamePopoverHookPath, 'utf8') : ''
  const groupControlsPath = 'src/components/PersonalSpaceWorkspace/PersonalAssetGroupControls.tsx'
  const groupControlsSource = existsSync(groupControlsPath) ? readFileSync(groupControlsPath, 'utf8') : ''
  const groupTransferControlPath = 'src/components/PersonalSpaceWorkspace/PersonalResourceGroupTransferControl.tsx'
  const groupTransferControlSource = existsSync(groupTransferControlPath) ? readFileSync(groupTransferControlPath, 'utf8') : ''
  const resourceGroupsHookPath = 'src/components/PersonalSpaceWorkspace/usePersonalResourceGroups.ts'
  const resourceGroupsHookSource = existsSync(resourceGroupsHookPath) ? readFileSync(resourceGroupsHookPath, 'utf8') : ''

  assert.match(hookSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createPersonalSpaceDerivedState/)
  assert.match(derivedSource, /const resourceSections/)
  assert.match(derivedSource, /title: '公共图片'/)
  assert.match(derivedSource, /title: '精灵图'/)
  assert.match(derivedSource, /title: '配音'/)
  assert.doesNotMatch(derivedSource, /title: '地图素材'/)
  assert.doesNotMatch(derivedSource, /title: '特效素材'/)
  assert.match(derivedSource, /assets: imageAssets/)
  assert.match(derivedSource, /assets: spriteAssets/)
  assert.match(derivedSource, /assets: voiceAssets/)
  assert.match(source, /label: '素材'/)
  assert.match(source, /<PersonalMaterialsPanel/)
  assert.match(materialsPanelSource, /label: '公共图片'/)
  assert.match(materialsPanelSource, /label: '精灵图'/)
  assert.match(materialsPanelSource, /label: '配音'/)
  assert.match(materialsPanelSource, /resourceSections\.filter\(\(section\) => section\.kind === 'image'\)\.map\(materialSection\)/)
  assert.match(materialsPanelSource, /resourceSections\.filter\(\(section\) => section\.kind === 'sprite'\)\.map\(materialSection\)/)
  assert.match(materialsPanelSource, /resourceSections\.filter\(\(section\) => section\.kind === 'voice'\)\.map\(materialSection\)/)
  assert.match(materialsPanelSource, /key=\{`material-\$\{section\.kind\}`\}/)
  assert.match(source, /key: 'materials'/)
  assert.match(materialsPanelSource, /<PersonalResourceSection/)
  assert.ok(existsSync(groupControlsPath), 'asset group controls component should exist')
  assert.match(sectionsSource, /from '\.\/PersonalAssetGroupControls'/)
  assert.match(groupControlsSource, /function PersonalAssetGroupControls/)
  assert.match(sectionsSource, /onAddGroup/)
  assert.equal(existsSync(createNamePopoverHookPath), true)
  assert.match(createNamePopoverHookSource, /export function useCreateNamePopover/)
  assert.match(groupControlsSource, /useCreateNamePopover/)
  assert.doesNotMatch(sectionsSource, /useCreateNamePopover/)
  assert.doesNotMatch(sectionsSource, /creatingGroup/)
  assert.match(groupControlsSource, /group-create-popover/)
  assert.match(groupControlsSource, /from '\.\/CreateNamePopoverButton'/)
  assert.match(groupControlsSource, /<CreateNamePopoverButton/)
  assert.doesNotMatch(groupControlsSource, /content=\{\(\s*<div className="voice-group-rename-popover/)
  assert.match(sectionsSource, /onChangeGroupName/)
  assert.match(sectionsSource, /onDeleteGroup/)
  assert.doesNotMatch(source, /const renderResourceSection = /)
  assert.doesNotMatch(source, /section\.assets\.map/)
  assert.match(sectionsSource, /function PersonalResourceSection/)
  assert.match(sectionsSource, /from '\.\/PersonalResourceAssetRecord'/)
  assert.match(sectionsSource, /from '\.\/PersonalResourceGroupBlock'/)
  assert.match(sectionsSource, /from '\.\/PersonalSpaceFilterControl'/)
  assert.doesNotMatch(sectionsSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.ok(existsSync(resourceGroupsHookPath), 'personal resource group state hook should exist')
  assert.match(sectionsSource, /from '\.\/usePersonalResourceGroups'/)
  assert.doesNotMatch(sectionsSource, /from '\.\/useRecentStarredFilter'/)
  assert.match(resourceGroupsHookSource, /export function usePersonalResourceGroups/)
  assert.match(resourceGroupsHookSource, /from '\.\/useRecentStarredFilter'/)
  assert.match(sectionsSource, /<PersonalResourceAssetRecord/)
  assert.match(sectionsSource, /<PersonalResourceGroupBlock/)
  assert.match(sectionsSource, /<PersonalSpaceFilterControl/)
  assert.doesNotMatch(sectionsSource, /<PersonalSpaceTextPopover/)
  assert.match(assetRecordSource, /export function PersonalResourceAssetRecord/)
  assert.match(assetRecordSource, /from '\.\/PersonalAssetPreview'/)
  assert.match(groupBlockSource, /export function PersonalResourceGroupBlock/)
  assert.match(groupBlockSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.ok(existsSync(groupTransferControlPath), 'resource group transfer control component should exist')
  assert.match(groupBlockSource, /from '\.\/PersonalResourceGroupTransferControl'/)
  assert.match(groupBlockSource, /<PersonalResourceGroupTransferControl/)
  assert.doesNotMatch(groupBlockSource, /function VoiceGroupTransferControl/)
  assert.doesNotMatch(groupBlockSource, /useState/)
  assert.doesNotMatch(groupBlockSource, /Modal\.confirm/)
  assert.doesNotMatch(groupBlockSource, /Dropdown/)
  assert.doesNotMatch(groupBlockSource, /DownOutlined/)
  assert.match(groupTransferControlSource, /export function PersonalResourceGroupTransferControl/)
  assert.match(groupTransferControlSource, /useState/)
  assert.match(groupTransferControlSource, /Modal\.confirm/)
  assert.match(groupTransferControlSource, /Dropdown/)
  assert.match(groupTransferControlSource, /DownOutlined/)
  assert.doesNotMatch(sectionsSource, /onTransferGroup/)
  assert.match(filterSource, /export function PersonalSpaceFilterControl/)
  assert.match(filterSource, /showSearch/)
  assert.match(filterSource, /filterOption/)
  assert.match(filterSource, /筛选/)
  assert.match(filterSource, /仅星标/)
  assert.match(filterSource, /SyncOutlined/)
  assert.match(filterSource, /onRefresh/)
  assert.match(materialsPanelSource, /onRefreshProjectData/)
  assert.match(sectionsSource, /onRefreshProjectData/)
  assert.match(recentStarredFilterSource, /recentFilterOptions/)
  assert.match(resourceGroupsHookSource, /visibleItems: visibleResourceGroups/)
  assert.doesNotMatch(sectionsSource, /slice\(-20\)\.reverse\(\)/)
  assert.doesNotMatch(sectionsSource, /setSelectedGroup\('全部分组'\)/)
  assert.doesNotMatch(sectionsSource, /onlyStarredGroups/)
  assert.match(textPopoverSource, /export function PersonalSpaceTextPopover/)
  assert.match(textPopoverSource, /<Popover/)
  assert.match(textPopoverSource, /<Input/)
  assert.match(textPopoverSource, /onPressEnter/)
  assert.doesNotMatch(textPopoverSource, /onPressEnter=\{onConfirm\}/)
  assert.match(textPopoverSource, /confirmDisabled/)
  assert.match(textPopoverSource, /voice-group-rename-popover/)
  assert.match(textPopoverSource, /确认/)
  assert.match(textPopoverSource, /取消/)
  assert.doesNotMatch(sectionsSource, /from '\.\/PersonalAssetPreview'/)
  assert.doesNotMatch(sectionsSource, /export function PersonalAssetPreview/)
  assert.doesNotMatch(sectionsSource, /readStoredResourceBlob/)
  assert.doesNotMatch(sectionsSource, /loadPersistedPersonalSpaceDirectoryHandle/)
  assert.doesNotMatch(sectionsSource, /asset-record-row/)
  assert.doesNotMatch(sectionsSource, /voice-record-fields/)
  assert.doesNotMatch(sectionsSource, /voice-dialogue-input/)
  assert.doesNotMatch(sectionsSource, /关联配音素材/)
  assert.doesNotMatch(sectionsSource, /DeleteOutlined/)
  assert.match(previewSource, /export function PersonalAssetPreview/)
  assert.match(previewSource, /useStoredResourcePreviewSource/)
  assert.match(previewSource, /useStoredAssetCoverSource/)
  assert.match(previewSource, /projectObjectStorage/)
  assert.match(previewSource, /spriteFrameModalStyle/)
  const resourceSectionBody = sectionsSource.slice(sectionsSource.indexOf('export function PersonalResourceSection'))
  assert.doesNotMatch(resourceSectionBody, /const \[selectedGroup, setSelectedGroup\] = useState/)
  assert.match(resourceSectionBody, /const resourceGroups = usePersonalResourceGroups\(section\)/)
  assert.doesNotMatch(resourceSectionBody, /selectedFilter: selectedGroup/)
  assert.doesNotMatch(resourceSectionBody, /setSelectedFilter: setSelectedGroup/)
  assert.doesNotMatch(resourceSectionBody, /const \[selectedAssetIdsByGroup, setSelectedAssetIdsByGroup\] = useState/)
  assert.doesNotMatch(resourceSectionBody, /setSelectedAssetIdsByGroup/)
  assert.match(resourceGroupsHookSource, /const \[selectedAssetIdsByGroup, setSelectedAssetIdsByGroup\] = useState/)
  assert.match(resourceSectionBody, /resourceGroups\.selectedAssetIdsForGroup\(item\.groupName\)\.includes\(item\.id\)/)
  assert.match(resourceSectionBody, /onSelectedChange=\{\(checked\) => resourceGroups\.toggleAssetSelected\(item, checked\)\}/)
  assert.match(resourceSectionBody, /selectedAssetIds/)
  assert.match(resourceGroupsHookSource, /const isVoiceSection = section\.kind === 'voice'/)
  assert.match(resourceGroupsHookSource, /const isGroupedResourceSection = section\.kind === 'image' \|\| section\.kind === 'sprite' \|\| isVoiceSection/)
  assert.doesNotMatch(resourceSectionBody, /visibleItems: visibleResourceGroups/)
  assert.doesNotMatch(resourceSectionBody, /slice\(-\d+\)\.reverse\(\)/)
  assert.match(resourceSectionBody, /voice-group-filter/)
  assert.doesNotMatch(resourceSectionBody, /filterOption\s*=/)
  assert.match(resourceGroupsHookSource, /最近创建的\d+个分组/)
  assert.match(resourceSectionBody, /voice-group-toolbar/)
  assert.match(groupBlockSource, /voice-group-block/)
  assert.match(groupBlockSource, /voice-group-header/)
  assert.match(groupBlockSource, /voice-group-left-actions/)
  assert.match(groupBlockSource, /voice-group-right-actions/)
  assert.match(groupBlockSource, /<div className="voice-group-right-actions">[\s\S]*删除分组[\s\S]*<\/div>/)
  assert.match(groupBlockSource, /voice-group-actions/)
  assert.match(groupBlockSource, /voice-group-admin-actions/)
  assert.match(resourceSectionBody, /useRenameDrafts/)
  assert.doesNotMatch(resourceSectionBody, /setRenameGroupDrafts/)
  assert.doesNotMatch(resourceSectionBody, /renamingGroupName/)
  assert.match(resourceSectionBody, /resource-section--voice/)
  assert.match(groupBlockSource, /上传到分组/)
  assert.match(groupTransferControlSource, /转移并删除该分组/)
  assert.doesNotMatch(groupTransferControlSource, /转移资产并删除该分组/)
  assert.match(groupTransferControlSource, /onDeleteGroup\(kind, groupName, \{ transferToGroup: transferTo \}\)/)
  assert.match(resourceSectionBody, /onDeleteGroup=\{onDeleteGroup\}/)
  assert.match(groupBlockSource, /onConfirmRename/)
  assert.doesNotMatch(groupBlockSource, /onRenameGroup\(section\.kind, groupName, renameTo\)/)
  assert.doesNotMatch(groupBlockSource, /onRenameDraftSet/)
  assert.doesNotMatch(groupBlockSource, /onRenamingGroupNameChange/)
  assert.match(groupBlockSource, /onDeleteGroup\(section\.kind, groupName, \{ deleteAssets: true \}\)/)
  assert.match(groupTransferControlSource, /selectedAssetIds\.forEach/)
  assert.match(groupTransferControlSource, /onChangeGroupName\(assetId, transferTo\)/)
  assert.match(groupTransferControlSource, /disabled=\{!transferTo \|\| selectedAssetIds\.length === 0\}/)
  assert.match(groupBlockSource, /commonResourceUploadProps\(section\.kind, groupName\)/)
  assert.match(groupBlockSource, /spriteResourceUploadProps\(groupName\)/)
  assert.match(resourceSectionBody, /resourceGroups\.isGroupedResourceSection \?/)
  assert.doesNotMatch(resourceSectionBody, /!isVoiceSection && groupAssets\.length === 0/)
  assert.match(resourceSectionBody, /value=\{resourceGroups\.selectedGroup\}/)
  assert.match(resourceSectionBody, /onChange=\{resourceGroups\.setSelectedGroup\}/)
  assert.match(resourceGroupsHookSource, /const groupAssets = section\.assets\.filter\(\(item\) => item\.groupName === selectedGroup\)/)
  assert.match(previewSource, /preview-image/)
  assert.match(previewSource, /audioRef/)
  assert.match(previewSource, /spritePlaying/)
  assert.match(previewSource, /spriteFrameIndex/)
  assert.match(previewSource, /window\.setInterval/)
  assert.match(assetRecordSource, /asset-selection-checkbox/)
  assert.match(assetRecordSource, /PersonalAssetPreview/)
  assert.match(assetRecordSource, /DeleteOutlined/)
  assert.match(assetRecordSource, /导入时间/)
  assert.match(sectionsSource, /resourceGroups\.groupAssets\.map/)
  assert.match(groupBlockSource, /全选/)
  assert.match(groupBlockSource, /取消全选/)
  assert.match(groupBlockSource, /删除选中资产/)
  assert.match(groupBlockSource, /selectedAssetIds\.forEach\(\(assetId\) => onDeleteAsset\(assetId\)\)/)
  assert.match(groupBlockSource, /disabled=\{selectedAssetIds\.length === 0\}/)
  assert.match(groupBlockSource, /onClearSelectedAssetIds/)
  assert.doesNotMatch(sectionsSource, /addonBefore="标签"/)
  assert.doesNotMatch(sectionsSource, /aria-label=\{`\$\{section\.title\}标签`\}/)
  assert.doesNotMatch(sectionsSource, /aria-label=\{`\$\{section\.title\}分组`\}/)
  assert.match(assetRecordSource, /关联配音素材/)
  assert.match(assetRecordSource, /关联角色/)
  assert.match(assetRecordSource, /关联剧情组/)
  assert.match(sectionsSource, /voice-resource-list/)
  assert.match(sectionsSource, /voice-group-list/)
  assert.match(sectionsSource, /voice-resource-panel/)
  assert.match(assetRecordSource, /voice-space-record/)
  assert.match(assetRecordSource, /voice-record-fields/)
  assert.match(assetRecordSource, /剧情顺序/)
  assert.match(personalSpaceCssSource, /\.voice-group-actions\s*\{[^}]*flex-wrap: nowrap;/)
  assert.match(personalSpaceCssSource, /\.voice-group-right-actions\s*\{[^}]*flex-wrap: nowrap;/)
  assert.doesNotMatch(source, /label: '图片'/)
  assert.doesNotMatch(sectionsSource, /未绑定本地文件/)
  assert.doesNotMatch(sectionsSource, /resourcePaths\.join/)
  assert.doesNotMatch(source, /key: 'assets'/)
  assert.doesNotMatch(source, /label: '通用资源管理'/)
  assert.doesNotMatch(source, /label: '地图素材'/)
  assert.doesNotMatch(source, /label: '特效素材'/)
  assert.doesNotMatch(source, /<strong>地图素材 \/ 特效素材 \/ 配音素材<\/strong>/)
  assert.doesNotMatch(source, /space\.assets\.map\(\(item\)/)
})
