import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('personal space workspace delegates asset upload and export actions', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceAssetActions.ts', 'utf8')
  const uploadPropsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceUploadProps.ts', 'utf8')
  const uploadActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceAssetUploadActions.ts', 'utf8')

  assert.match(workspaceSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createPersonalSpaceAssetActions/)
  assert.match(actionsSource, /export function createPersonalSpaceAssetActions/)
  assert.match(actionsSource, /exportStoryboardWithStatus/)
  assert.match(actionsSource, /uploadCharacterPortrait/)
  assert.match(actionsSource, /uploadCharacterSprite/)
  assert.match(actionsSource, /uploadCharacterVoice/)
  assert.match(actionsSource, /uploadStoryboardVoice/)
  assert.match(actionsSource, /uploadCommonResource/)
  assert.match(actionsSource, /deleteAsset/)
  assert.match(actionsSource, /portraitUploadProps/)
  assert.match(actionsSource, /spriteUploadProps/)
  assert.match(actionsSource, /voiceUploadProps/)
  assert.match(actionsSource, /storyboardVoiceUploadProps/)
  assert.match(actionsSource, /commonResourceUploadProps/)
  assert.match(actionsSource, /imageSpriteUploadProps/)
  assert.match(actionsSource, /createPersonalSpaceUploadProps/)
  assert.doesNotMatch(actionsSource, /createSpriteUploadBatch/)
  assert.doesNotMatch(actionsSource, /consumeSpriteUploadBatch/)
  assert.doesNotMatch(actionsSource, /createRecordSpriteUploadBatchTracker/)
  assert.doesNotMatch(actionsSource, /createNullableSpriteUploadBatchTracker/)
  assert.match(uploadPropsSource, /createSpriteUploadBatch/)
  assert.match(uploadPropsSource, /consumeSpriteUploadBatch/)
  assert.match(uploadPropsSource, /createRecordSpriteUploadBatchTracker/)
  assert.match(uploadPropsSource, /createNullableSpriteUploadBatchTracker/)
  assert.equal((uploadPropsSource.match(/consumeSpriteUploadBatch/g) ?? []).length, 2)
  assert.match(uploadPropsSource, /function handleSpriteUploadChange\(/)
  assert.equal((uploadPropsSource.match(/window\.setTimeout/g) ?? []).length, 1)
  assert.doesNotMatch(actionsSource, /get current\(\)/)
  assert.match(actionsSource, /exportStoryboardVoiceAssetsToTarget/)
  assert.match(uploadActionsSource, /createSpriteAssetForUpload/)
  assert.match(actionsSource, /deleteAssetWithOptionalResources/)
  assert.doesNotMatch(workspaceSource, /const exportStoryboardWithStatus = async/)
  assert.doesNotMatch(workspaceSource, /const uploadCharacterPortrait = async/)
  assert.doesNotMatch(workspaceSource, /const uploadCommonResource = async/)
  assert.doesNotMatch(workspaceSource, /const imageSpriteUploadProps = /)
})

test('personal space workspace delegates edit actions for characters storyboards and groups', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceEditActions.ts', 'utf8')

  assert.match(workspaceSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createPersonalSpaceEditActions/)
  assert.match(actionsSource, /export function createPersonalSpaceEditActions/)
  assert.match(actionsSource, /renameCharacter/)
  assert.match(actionsSource, /assignAsset/)
  assert.match(actionsSource, /assignStoryboardVoiceCharacter/)
  assert.match(actionsSource, /changeEffectVoiceLinks/)
  assert.match(actionsSource, /deleteAssetGroup/)
  assert.match(actionsSource, /setDeleteResourcesWithContent/)
  assert.doesNotMatch(workspaceSource, /renameCharacter:\s*\(characterId/)
  assert.doesNotMatch(workspaceSource, /assignAsset:\s*\(characterId/)
  assert.doesNotMatch(workspaceSource, /assignStoryboardVoiceCharacter:\s*\(groupId/)
  assert.doesNotMatch(workspaceSource, /changeEffectVoiceLinks:\s*\(assetId/)
  assert.doesNotMatch(workspaceSource, /deleteAssetGroup:\s*\(kind/)
  assert.doesNotMatch(workspaceSource, /setDeleteResourcesWithContent:\s*\(/)
})

test('matte task groups can export group images and collect them to public image assets', () => {
  const source = readFileSync('src/components/MultiFrameSpriteWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/MultiFrameSpriteWorkspace/MatteWorkspacePanel.tsx', 'utf8')
  const hookSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useMattePipeline.ts', 'utf8')
  const processingHookSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useMatteProcessingQueue.ts', 'utf8')
  const groupActionsSource = readFileSync('src/components/MultiFrameSpriteWorkspace/matteGroupActions.ts', 'utf8')

  assert.match(panelSource, /导出组图片/)
  assert.match(panelSource, /收藏到项目空间/)
  assert.match(panelSource, /personalSpaceCollectEnabled/)
  assert.match(panelSource, /personalSpaceCollectDisabledReason/)
  assert.match(panelSource, /disabled=\{!personalSpaceCollectEnabled\}/)
  assert.match(panelSource, /应用到组所有帧/)
  assert.doesNotMatch(panelSource, /确定应用到该组所有帧/)
  assert.doesNotMatch(panelSource, /导出抠图/)
  assert.doesNotMatch(panelSource, /导入到个人空间/)
  assert.match(panelSource, /onExportMatteGroup/)
  assert.match(panelSource, /onImportMatteGroupToPersonalSpace/)
  assert.match(hookSource, /exportMatteGroup/)
  assert.match(hookSource, /importMatteGroupToPersonalSpace/)
  assert.match(hookSource, /createMatteGroupActions/)
  assert.match(processingHookSource, /dequeueNextInactiveFrameId/)
  assert.doesNotMatch(processingHookSource, /\.findIndex\(\(queuedId\) => !.*ActiveRef\.current\.has\(queuedId\)\)/)
  assert.match(groupActionsSource, /项目空间-素材-公共图片/)
  assert.match(groupActionsSource, /JSZip/)
  assert.match(groupActionsSource, /persistCurrentProjectSpaceState/)
  assert.match(groupActionsSource, /showCurrentProjectSpaceSyncWarning/)
  assert.doesNotMatch(hookSource, /JSZip/)
  assert.doesNotMatch(hookSource, /persistCurrentProjectSpaceState/)
  assert.doesNotMatch(hookSource, /showCurrentProjectSpaceSyncWarning/)
  assert.doesNotMatch(hookSource, /writeCurrentProjectSpaceState/)
  assert.doesNotMatch(hookSource, /已保存到本地项目缓存，但同步项目存储失败/)
  assert.doesNotMatch(hookSource, /writePersonalSpaceState/)
  assert.match(groupActionsSource, /createResourceAssetFromUpload/)
  assert.doesNotMatch(hookSource, /createResourceAssetFromUpload/)
  assert.match(source, /workspace\.matte\.exportMatteGroup/)
  assert.match(source, /workspace\.matte\.importMatteGroupToPersonalSpace/)
  assert.match(source, /workspace\.personalSpaceCollectEnabled/)
  assert.match(groupActionsSource, /personalSpaceDirectoryRequiredMessage/)
  assert.doesNotMatch(groupActionsSource, /importMatteGroupToPersonalSpace[\s\S]*archiveAssetForStorageDirectory/)
})

test('project space external collectors share sync warning formatting', () => {
  const spriteCollectSource = readFileSync('src/components/MultiFrameSpriteWorkspace/useSpriteCollectWorkflow.ts', 'utf8')
  const matteGroupActionsSource = readFileSync('src/components/MultiFrameSpriteWorkspace/matteGroupActions.ts', 'utf8')
  const voiceCollectorSource = readFileSync('src/components/VoiceDeploymentWorkspace/voicePersonalSpaceCollector.ts', 'utf8')
  const voiceProjectSpaceHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceProjectSpaceActions.ts', 'utf8')
  const messageSource = readFileSync('src/components/PersonalSpaceWorkspace/projectSpacePersistenceMessages.ts', 'utf8')

  assert.match(messageSource, /formatCurrentProjectSpaceSyncWarning/)
  assert.match(messageSource, /showCurrentProjectSpaceSyncWarning/)
  for (const source of [spriteCollectSource, matteGroupActionsSource, voiceProjectSpaceHookSource]) {
    assert.match(source, /showCurrentProjectSpaceSyncWarning/)
    assert.doesNotMatch(source, /已保存到本地项目缓存，但同步项目存储失败/)
  }
  assert.doesNotMatch(voiceCollectorSource, /已保存到本地项目缓存，但同步项目存储失败/)
})

test('project character pickers and storyboard avatars resolve remote assets through preview helpers', () => {
  const pickerSource = readFileSync('src/components/PersonalSpaceWorkspace/CharacterAssetPicker.tsx', 'utf8')
  const previewSourceHook = readFileSync('src/components/PersonalSpaceWorkspace/useStoredResourcePreviewSource.ts', 'utf8')
  const avatarSource = readFileSync('src/components/PersonalSpaceWorkspace/StoryboardCharacterAvatar.tsx', 'utf8')
  const resolverSource = readFileSync('src/components/PersonalSpaceWorkspace/projectAssetResourceResolver.ts', 'utf8')

  assert.match(pickerSource, /useStoredAssetCoverSource/)
  assert.match(previewSourceHook, /resolveProjectAssetResourceSource/)
  assert.match(previewSourceHook, /buildProjectAssetResourceRef/)
  assert.match(previewSourceHook, /buildProjectAssetCoverResourceRef/)
  assert.doesNotMatch(pickerSource, /resolveProjectAssetResourceSource/)
  assert.doesNotMatch(pickerSource, /buildProjectAssetResourceRef/)
  assert.doesNotMatch(pickerSource, /URL\.revokeObjectURL/)
  assert.match(avatarSource, /useStoredAssetCoverSource/)
  assert.match(avatarSource, /enabled: Boolean\(portrait\)/)
  assert.doesNotMatch(avatarSource, /\?\s*useStoredAssetCoverSource/)
  assert.doesNotMatch(avatarSource, /resolveProjectAssetResourceSource/)
  assert.doesNotMatch(avatarSource, /buildProjectAssetResourceRef/)
  assert.doesNotMatch(avatarSource, /URL\.revokeObjectURL/)
  assert.match(resolverSource, /buildProjectAssetResourceRef/)
  assert.match(resolverSource, /buildProjectAssetCoverResourceRef/)
  assert.doesNotMatch(pickerSource, /<img src=\{asset\.resourcePaths\[0\]\}/)
  assert.doesNotMatch(avatarSource, /src=\{portraitPath\}/)
})
