import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('personal space workspace delegates character management panel', () => {
  const source = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceWorkbench.tsx', 'utf8')
  const panelSource = [
    readFileSync('src/components/PersonalSpaceWorkspace/PersonalCharacterPanel.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/CharacterProfileCard.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/CharacterAssetPicker.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/CharacterLinkedAssetColumn.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/CreateNamePopoverButton.tsx', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/useRecentStarredFilter.ts', 'utf8'),
    readFileSync('src/components/PersonalSpaceWorkspace/useRenameDrafts.ts', 'utf8'),
  ].join('\n')
  const characterPanelSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalCharacterPanel.tsx', 'utf8')
  const createNamePopoverSource = readFileSync('src/components/PersonalSpaceWorkspace/CreateNamePopoverButton.tsx', 'utf8')
  const createNamePopoverHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useCreateNamePopover.ts', 'utf8')
  const characterProfileCardSource = readFileSync('src/components/PersonalSpaceWorkspace/CharacterProfileCard.tsx', 'utf8')
  const linkedAssetColumnSource = readFileSync('src/components/PersonalSpaceWorkspace/CharacterLinkedAssetColumn.tsx', 'utf8')
  const recentStarredFilterSource = readFileSync('src/components/PersonalSpaceWorkspace/useRecentStarredFilter.ts', 'utf8')
  const renameDraftsSource = readFileSync('src/components/PersonalSpaceWorkspace/useRenameDrafts.ts', 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const derivedSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceDerivedState.ts', 'utf8')
  const personalSpaceCssSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpace.characterControls.css', 'utf8')

  assert.match(source, /from '\.\/PersonalCharacterPanel'/)
  assert.match(source, /<PersonalCharacterPanel/)
  assert.match(panelSource, /from '\.\/CharacterAssetPicker'/)
  assert.match(characterPanelSource, /from '\.\/CharacterProfileCard'/)
  assert.match(characterPanelSource, /<CharacterProfileCard/)
  assert.match(characterProfileCardSource, /export function CharacterProfileCard/)
  assert.match(characterProfileCardSource, /from '\.\/CharacterLinkedAssetColumn'/)
  assert.match(characterProfileCardSource, /<CharacterLinkedAssetColumn/)
  assert.match(linkedAssetColumnSource, /function CharacterLinkedAssetColumn/)
  assert.match(source, /onRenameAsset=\{workspace\.renameAsset\}/)
  assert.match(characterPanelSource, /onRenameAsset/)
  assert.match(characterProfileCardSource, /onRenameAsset/)
  assert.match(linkedAssetColumnSource, /onRenameAsset/)
  assert.match(linkedAssetColumnSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.match(linkedAssetColumnSource, /EditOutlined/)
  assert.match(linkedAssetColumnSource, /<PersonalSpaceTextPopover/)
  assert.match(linkedAssetColumnSource, /重命名资产/)
  assert.doesNotMatch(source, /角色列表/)
  assert.doesNotMatch(source, /<strong>角色肖像<\/strong>/)
  assert.doesNotMatch(source, /<strong>角色精灵图<\/strong>/)
  assert.doesNotMatch(source, /<strong>角色配音<\/strong>/)
  assert.match(panelSource, /function PersonalCharacterPanel/)
  assert.match(panelSource, /from '\.\/PersonalSpaceFilterControl'/)
  assert.match(panelSource, /from '\.\/PersonalSpaceTextPopover'/)
  assert.match(panelSource, /<PersonalSpaceFilterControl/)
  assert.match(panelSource, /<PersonalSpaceTextPopover/)
  assert.match(createNamePopoverSource, /export function CreateNamePopoverButton/)
  assert.match(createNamePopoverSource, /PersonalSpaceTextPopover/)
  assert.match(createNamePopoverSource, /confirmDisabled=\{!value\.trim\(\)\}/)
  assert.match(createNamePopoverHookSource, /export function useCreateNamePopover/)
  assert.match(characterPanelSource, /from '\.\/CreateNamePopoverButton'/)
  assert.match(characterPanelSource, /from '\.\/useCreateNamePopover'/)
  assert.match(characterPanelSource, /<CreateNamePopoverButton/)
  assert.doesNotMatch(characterPanelSource, /<PersonalSpaceTextPopover/)
  assert.match(characterPanelSource, /useCreateNamePopover/)
  assert.doesNotMatch(characterPanelSource, /creatingCharacter/)
  assert.match(panelSource, /character-create-popover/)
  assert.match(characterPanelSource, /useRecentStarredFilter/)
  assert.match(characterPanelSource, /selectedCharacterFilter/)
  assert.match(characterPanelSource, /visibleCharacters/)
  assert.match(recentStarredFilterSource, /recentFilterOptions/)
  assert.match(recentStarredFilterSource, /slice\(-20\)\.reverse\(\)/)
  assert.match(panelSource, /character-panel-toolbar/)
  assert.match(panelSource, /character-filter-control/)
  assert.match(panelSource, /最近创建的\d+个角色/)
  assert.doesNotMatch(characterPanelSource, /slice\(-20\)\.reverse\(\)/)
  assert.doesNotMatch(characterPanelSource, /setSelectedCharacterFilter\('全部角色'\)/)
  assert.doesNotMatch(characterPanelSource, /filterOption\s*=/)
  assert.match(renameDraftsSource, /export function useRenameDrafts/)
  assert.match(renameDraftsSource, /setRenamingId/)
  assert.match(renameDraftsSource, /draft\.trim\(\)/)
  assert.match(characterPanelSource, /useRenameDrafts/)
  assert.doesNotMatch(characterPanelSource, /setRenamingCharacterId/)
  assert.doesNotMatch(characterPanelSource, /setCharacterNameDrafts/)
  assert.match(characterProfileCardSource, /EditOutlined/)
  assert.match(characterProfileCardSource, /角色名称/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover character-create-popover/)
  assert.doesNotMatch(panelSource, /content=\{\(\s*<div className="voice-group-rename-popover character-name-rename-popover/)
  assert.doesNotMatch(panelSource, /className="character-name-input"[\s\S]*onChange=\{\(event\) => onRenameCharacter/)
  assert.doesNotMatch(panelSource, /<strong>角色列表<\/strong>/)
  assert.doesNotMatch(panelSource, /<span className="section-caption">角色列表<\/span>/)
  assert.match(characterProfileCardSource, /角色肖像/)
  assert.match(characterProfileCardSource, /角色精灵图/)
  assert.match(characterProfileCardSource, /角色配音/)
  assert.match(characterProfileCardSource, /上传肖像/)
  assert.match(hookSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createPersonalSpaceDerivedState/)
  assert.match(derivedSource, /const portraitAssets = space\.assets\.filter\(\(asset\) => asset\.kind === 'image' && asset\.assetSubtype === 'portrait'\)/)
  assert.match(panelSource, /function CharacterAssetPicker/)
  assert.match(panelSource, /character-link-actions/)
  assert.match(panelSource, /关联肖像/)
  assert.match(panelSource, /portrait-picker-popover/)
  assert.match(panelSource, /selectedAssetId/)
  assert.match(panelSource, /确认关联肖像/)
  assert.match(panelSource, /确认关联精灵图/)
  assert.match(panelSource, /确认关联配音/)
  assert.doesNotMatch(panelSource, /placeholder="关联肖像资源"/)
  assert.doesNotMatch(panelSource, /placeholder="关联精灵图资源"/)
  assert.doesNotMatch(panelSource, /placeholder="关联配音资源"/)
  assert.doesNotMatch(panelSource, /角色肖像标签/)
  assert.doesNotMatch(panelSource, /角色精灵图标签/)
  assert.doesNotMatch(panelSource, /未设置标签/)
  assert.match(panelSource, /PersonalAssetPreview/)
  assert.doesNotMatch(panelSource, /关联备注/)
  assert.doesNotMatch(panelSource, /noteName/)
  assert.match(panelSource, /取消关联/)
  assert.match(panelSource, /DisconnectOutlined/)
  assert.match(panelSource, /onUnassignAsset/)
  assert.match(panelSource, /onMoveCharacterVoice/)
  assert.match(panelSource, /draggable/)
  assert.match(panelSource, /onDrop/)
  assert.doesNotMatch(characterPanelSource, /PersonalAssetPreview/)
  assert.doesNotMatch(characterPanelSource, /DisconnectOutlined/)
  assert.doesNotMatch(characterPanelSource, /draggable/)
  assert.doesNotMatch(characterPanelSource, /character-record-header/)
  assert.doesNotMatch(characterPanelSource, /<CharacterLinkedAssetColumn/)
  assert.match(linkedAssetColumnSource, /PersonalAssetPreview/)
  assert.match(linkedAssetColumnSource, /DisconnectOutlined/)
  assert.match(linkedAssetColumnSource, /draggable/)
  assert.doesNotMatch(panelSource, /onReorderCharacterVoice/)
  assert.doesNotMatch(panelSource, /角色配音标签/)
  assert.doesNotMatch(panelSource, /角色配音关联备注/)
  assert.match(linkedAssetColumnSource, /asset\?\.dialogueText/)
  assert.match(characterProfileCardSource, /unlinkAriaLabel="取消关联角色肖像"/)
  assert.match(characterProfileCardSource, /unlinkAriaLabel="取消关联角色精灵图"/)
  assert.match(characterProfileCardSource, /unlinkAriaLabel="取消关联角色配音"/)
  assert.match(linkedAssetColumnSource, /aria-label=\{unlinkAriaLabel\}/)
  assert.match(personalSpaceCssSource, /\.character-panel-toolbar\s*\{[^}]*display: flex;/)
  assert.match(personalSpaceCssSource, /\.character-filter-control,\s*\.storyboard-filter-control\s*\{[^}]*display: flex;/)
})
