import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

test('remote project workspace changes sync through project storage service', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const lifecycleSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceLifecycle.ts', 'utf8')
  const remoteSyncSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectRemoteSync.ts', 'utf8')
  const storageWorkflowSource = readFileSync('src/components/PersonalSpaceWorkspace/projectStorageWorkflow.ts', 'utf8')
  const migrationServiceSource = readFileSync('src/components/ProjectStorage/projectMigrationService.ts', 'utf8')

  assert.match(migrationServiceSource, /repository\?: ProjectRepository/)
  assert.match(migrationServiceSource, /objectStorage\?: ProjectObjectStorage/)
  assert.match(remoteSyncSource, /createProjectRemoteSyncQueue/)
  assert.match(remoteSyncSource, /queuedRemoteSyncRef\.current\.enqueue\(project, nextSpace\)/)
  assert.match(remoteSyncSource, /for \(const entry of queuedEntries\)/)
  assert.match(remoteSyncSource, /syncProjectStateToStorage\(entry\.project, entry\.state\)/)
  assert.doesNotMatch(remoteSyncSource, /queuedRemoteSyncSpaceRef/)
  assert.match(remoteSyncSource, /project\?\.mode !== 'remote'/)
  assert.match(workspaceSource, /projectStorageWorkflow\.syncProjectStateToStorage/)
  assert.match(storageWorkflowSource, /repository: options\.remoteRepository/)
  assert.match(storageWorkflowSource, /objectStorage: options\.remoteObjectStorage/)
  assert.match(storageWorkflowSource, /assetManager: options\.assetManager/)
  assert.match(storageWorkflowSource, /storageProvider: 'qiniu_kodo'/)
  assert.match(storageWorkflowSource, /const remoteSettings = options\.getRemoteSettings\(project\.id\)/)
  assert.match(storageWorkflowSource, /databaseProvider: remoteSettings\.database_provider/)
  assert.match(storageWorkflowSource, /remoteDatabaseProfileId: null/)
  assert.match(storageWorkflowSource, /remoteStorageProfileId: null/)
  assert.doesNotMatch(workspaceSource, /databaseProvider: settingsWorkspace\.databaseProfileDraft\.provider,\s*remoteDatabaseProfileId: settingsWorkspace\.selectedDatabaseProfileId,\s*remoteStorageProfileId: settingsWorkspace\.selectedKodoProfileId/)
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceLifecycle/)
  assert.match(lifecycleSource, /scheduleRemoteProjectSync\(space\)/)
})

test('project workspace keeps manual sync retry in the status panel instead of the header', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const remoteSyncSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectRemoteSync.ts', 'utf8')
  const workbenchSource = readFileSync('src/components/PersonalSpaceWorkspace/PersonalSpaceWorkbench.tsx', 'utf8')
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteSyncStatusPanel.tsx', 'utf8')

  assert.match(workspaceSource, /useProjectRemoteSync/)
  assert.doesNotMatch(workspaceSource, /manualSyncInFlightProjectIdRef/)
  assert.match(remoteSyncSource, /const \[syncingProjectId, setSyncingProjectId\] = useState\(''\)/)
  assert.match(remoteSyncSource, /const manualSyncInFlightProjectIdRef = useRef\(''\)/)
  assert.match(remoteSyncSource, /const syncActiveProjectNow = async \(\)/)
  assert.match(remoteSyncSource, /if \(manualSyncInFlightProjectIdRef\.current\)/)
  assert.match(remoteSyncSource, /setSyncingProjectId\(syncProjectId\)/)
  assert.match(remoteSyncSource, /messageApi\.success\('已同步项目空间'\)/)
  assert.match(workspaceSource, /syncingProjectId/)
  assert.match(workspaceSource, /syncActiveProjectNow/)
  assert.doesNotMatch(workbenchSource, /SyncOutlined/)
  assert.doesNotMatch(workbenchSource, /同步项目/)
  assert.match(workbenchSource, /onRetryActiveProject=\{workspace\.syncActiveProjectNow\}/)
  assert.match(panelSource, /重试同步/)
  assert.match(panelSource, /loading=\{Boolean\(activeProjectId\) && retryingProjectId === activeProjectId\}/)
})

test('project remote sync status panel renders for pending upload, active sync, and failed retry states', () => {
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteSyncStatusPanel.tsx', 'utf8')
  const modelSource = readFileSync('src/components/PersonalSpaceWorkspace/projectRemoteSyncStatusModel.ts', 'utf8')

  assert.match(panelSource, /shouldShowProjectRemoteSyncStatus/)
  assert.match(panelSource, /if \(!shouldShowProjectRemoteSyncStatus\(status\)\) return null/)
  assert.match(panelSource, /status\.pendingUploadCount/)
  assert.match(modelSource, /status\.pendingUploadCount > 0/)
  assert.match(modelSource, /status\.activeTaskCount > 0/)
  assert.match(modelSource, /task\.status === 'failed'/)
})

test('remote project realtime sync is debounced and has a periodic fallback', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const lifecycleSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceLifecycle.ts', 'utf8')
  const remoteSyncSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectRemoteSync.ts', 'utf8')

  assert.match(remoteSyncSource, /REMOTE_PROJECT_SYNC_DEBOUNCE_MS/)
  assert.match(remoteSyncSource, /REMOTE_PROJECT_PERIODIC_SYNC_MS/)
  assert.match(remoteSyncSource, /const remoteSyncTimerRef = useRef/)
  assert.match(remoteSyncSource, /const queuedRemoteSyncRef = useRef\(createProjectRemoteSyncQueue<PersonalSpaceState>\(\)\)/)
  assert.match(remoteSyncSource, /const pending = new Map<string, QueuedProjectRemoteSync<State>>\(\)/)
  assert.match(remoteSyncSource, /const remoteSyncInFlightRef = useRef\(false\)/)
  assert.match(remoteSyncSource, /const optionsRef = useRef\(options\)/)
  assert.match(remoteSyncSource, /optionsRef\.current = options/)
  assert.match(remoteSyncSource, /const flushQueuedRemoteSync = async \(\)/)
  assert.match(remoteSyncSource, /const scheduleRemoteProjectSync = \(\s*nextSpace: PersonalSpaceState,\s*delay = REMOTE_PROJECT_SYNC_DEBOUNCE_MS,/)
  assert.match(remoteSyncSource, /remoteSyncTimerRef\.current = window\.setTimeout/)
  assert.match(remoteSyncSource, /void flushQueuedRemoteSync\(\)/)
  assert.match(remoteSyncSource, /\}, delay\)/)
  assert.match(remoteSyncSource, /remoteSyncIntervalRef\.current = window\.setInterval/)
  assert.match(remoteSyncSource, /scheduleRemoteProjectSync\(optionsRef\.current\.getCurrentSpace\(\), 0\)/)
  assert.match(remoteSyncSource, /\}, REMOTE_PROJECT_PERIODIC_SYNC_MS\)/)
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceLifecycle/)
  assert.match(lifecycleSource, /scheduleRemoteProjectSync\(space\)/)
  assert.doesNotMatch(workspaceSource, /remoteSyncIntervalRef/)
  assert.doesNotMatch(workspaceSource, /queuedRemoteSync/)
  assert.doesNotMatch(remoteSyncSource, /queuedRemoteSyncSpaceRef/)
  assert.doesNotMatch(workspaceSource, /void syncActiveProjectStateToStorage\(space\)/)
})
