import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

import { packageJsonSource } from './appStructureTestHelpers.test'

test('project management exposes remote database and qiniu kodo configuration', () => {
  const tabsPath = 'src/components/PersonalSpaceWorkspace/ProjectManagementTabs.tsx'
  const createTabPath = 'src/components/PersonalSpaceWorkspace/ProjectManagementCreateTab.tsx'
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementPanel.tsx', 'utf8')
  assert.ok(existsSync(tabsPath))
  const tabsSource = readFileSync(tabsPath, 'utf8')
  assert.ok(existsSync(createTabPath))
  const createTabSource = readFileSync(createTabPath, 'utf8')
  const createCardSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectCreateCard.tsx', 'utf8')
  const detailsCardSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectDetailsCard.tsx', 'utf8')
  const metadataFieldsSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectMetadataFields.tsx', 'utf8')
  const remoteSettingsSectionSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementRemoteSettingsSection.tsx', 'utf8')
  const remoteSettingsSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteSettingsPanel.tsx', 'utf8')
  const remoteDatabaseSettingsPath = 'src/components/PersonalSpaceWorkspace/ProjectRemoteDatabaseSettingsPanel.tsx'
  const remoteKodoSettingsPath = 'src/components/PersonalSpaceWorkspace/ProjectRemoteKodoSettingsPanel.tsx'
  const remoteProfileSaveButtonPath = 'src/components/PersonalSpaceWorkspace/ProjectRemoteProfileSaveButton.tsx'
  assert.ok(existsSync(remoteDatabaseSettingsPath))
  assert.ok(existsSync(remoteKodoSettingsPath))
  assert.ok(existsSync(remoteProfileSaveButtonPath))
  const remoteDatabaseSettingsSource = readFileSync(remoteDatabaseSettingsPath, 'utf8')
  const remoteKodoSettingsSource = readFileSync(remoteKodoSettingsPath, 'utf8')
  const remoteProfileSaveButtonSource = readFileSync(remoteProfileSaveButtonPath, 'utf8')
  const hookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')
  const remoteProfilesHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useRemoteConnectionProfilesWorkspace.ts', 'utf8')
  const remoteProfileActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/projectRemoteProfileActions.ts', 'utf8')
  const remoteProfileVerificationActionsSource = readFileSync(
    'src/components/PersonalSpaceWorkspace/projectRemoteProfileVerificationActions.ts',
    'utf8',
  )
  const remoteProfileDeleteActionsPath = 'src/components/PersonalSpaceWorkspace/projectRemoteProfileDeleteActions.ts'
  assert.ok(existsSync(remoteProfileDeleteActionsPath))
  const remoteProfileDeleteActionsSource = readFileSync(remoteProfileDeleteActionsPath, 'utf8')
  const remoteProfileWorkspaceModelPath = 'src/components/PersonalSpaceWorkspace/projectRemoteProfileWorkspaceModel.ts'
  assert.ok(existsSync(remoteProfileWorkspaceModelPath))
  const remoteProfileWorkspaceModelSource = readFileSync(remoteProfileWorkspaceModelPath, 'utf8')
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/projectManagementActions.ts', 'utf8')
  const updateRemoteProjectLinksSource = actionsSource.slice(
    actionsSource.indexOf('const updateRemoteProjectLinks = async'),
    actionsSource.indexOf('const deleteProject = async'),
  )
  const managementSurfaceSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementSurface.tsx', 'utf8')

  assert.match(panelSource, /ProjectManagementTabs/)
  assert.doesNotMatch(panelSource, /const renderRemoteProjectSettings = \(/)
  assert.doesNotMatch(panelSource, /<ProjectManagementRemoteSettingsSection/)
  assert.doesNotMatch(panelSource, /<ProjectManagementCreateTab/)
  assert.doesNotMatch(panelSource, /<ProjectCreateCard/)
  assert.doesNotMatch(panelSource, /const \[createMode/)
  assert.doesNotMatch(panelSource, /const \[remoteCreationProjectId/)
  assert.doesNotMatch(panelSource, /const \[newProjectName/)
  assert.doesNotMatch(panelSource, /const \[newProjectDescription/)
  assert.doesNotMatch(panelSource, /const createProject = async/)
  assert.match(tabsSource, /export function ProjectManagementTabs/)
  assert.match(tabsSource, /ProjectManagementCreateTab/)
  assert.match(tabsSource, /ProjectManagementRemoteSettingsSection/)
  assert.match(tabsSource, /ProjectDetailsCard/)
  assert.match(createTabSource, /export function ProjectManagementCreateTab/)
  assert.match(createTabSource, /ProjectCreateCard/)
  assert.match(createTabSource, /ProjectManagementRemoteSettingsSection/)
  assert.match(createTabSource, /createProjectId/)
  assert.match(createTabSource, /onCreateRemoteProject\(remoteCreationProjectId/)
  assert.match(createTabSource, /onCreateLocalProject\(name/)
  assert.match(createTabSource, /clearDirtySource\('projectCreation'\)/)
  assert.match(createCardSource, /export function ProjectCreateCard/)
  assert.match(createCardSource, /ProjectMetadataFields/)
  assert.match(createCardSource, /Segmented/)
  assert.match(createCardSource, /创建远程项目/)
  assert.doesNotMatch(createCardSource, /<Input/)
  assert.doesNotMatch(panelSource, /<Segmented/)
  assert.doesNotMatch(panelSource, /ProjectDetailsCard/)
  assert.match(tabsSource, /ProjectDetailsCard/)
  assert.match(detailsCardSource, /export function ProjectDetailsCard/)
  assert.match(detailsCardSource, /ProjectMetadataFields/)
  assert.match(detailsCardSource, /迁移到远程/)
  assert.match(detailsCardSource, /删除项目/)
  assert.match(detailsCardSource, /Switch/)
  assert.doesNotMatch(detailsCardSource, /<Input/)
  assert.match(metadataFieldsSource, /export function ProjectMetadataFields/)
  assert.doesNotMatch(panelSource, /<Switch/)
  assert.doesNotMatch(panelSource, /<Popconfirm/)
  assert.doesNotMatch(panelSource, /ProjectManagementRemoteSettingsSection/)
  assert.match(tabsSource, /ProjectManagementRemoteSettingsSection/)
  assert.doesNotMatch(panelSource, /ProjectRemoteSettingsPanel/)
  assert.doesNotMatch(panelSource, /databaseProfileOptions/)
  assert.doesNotMatch(panelSource, /kodoProfileOptions/)
  assert.doesNotMatch(panelSource, /const saveDatabaseProfile = async/)
  assert.match(remoteSettingsSectionSource, /ProjectRemoteSettingsPanel/)
  assert.match(remoteSettingsSectionSource, /databaseProfileOptions/)
  assert.match(remoteSettingsSectionSource, /kodoProfileOptions/)
  assert.match(remoteSettingsSectionSource, /const saveDatabaseProfile = async/)
  assert.match(remoteSettingsSectionSource, /onUpdateRemoteProjectLinks/)
  assert.match(remoteSettingsSource, /ProjectRemoteDatabaseSettingsPanel/)
  assert.match(remoteSettingsSource, /ProjectRemoteKodoSettingsPanel/)
  assert.doesNotMatch(remoteSettingsSource, /PostgreSQL/)
  assert.doesNotMatch(remoteSettingsSource, /Access Key/)
  assert.doesNotMatch(remoteSettingsSource, /测试失败，仍然保存/)
  assert.match(remoteDatabaseSettingsSource, /远程数据库/)
  assert.match(remoteDatabaseSettingsSource, /PostgreSQL/)
  assert.match(remoteDatabaseSettingsSource, /MySQL/)
  assert.match(remoteDatabaseSettingsSource, /测试连接/)
  assert.match(remoteDatabaseSettingsSource, /初始化表结构/)
  assert.match(remoteDatabaseSettingsSource, /删除数据库配置/)
  assert.match(remoteDatabaseSettingsSource, /ProjectRemoteProfileSaveButton/)
  assert.match(remoteKodoSettingsSource, /七牛 Kodo/)
  assert.match(remoteKodoSettingsSource, /Access Key/)
  assert.match(remoteKodoSettingsSource, /删除 Kodo 配置/)
  assert.match(remoteKodoSettingsSource, /验证 Kodo/)
  assert.match(remoteKodoSettingsSource, /ProjectRemoteProfileSaveButton/)
  assert.match(remoteProfileSaveButtonSource, /测试失败，仍然保存/)
  assert.match(detailsCardSource, /迁移到远程/)
  assert.match(remoteSettingsSource, /保存项目绑定/)
  assert.match(tabsSource, /selectedProject\.mode === 'remote'/)
  assert.match(managementSurfaceSource, /onUpdateRemoteProjectLinks=\{workspace\.updateRemoteProjectLinks\}/)
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createProjectManagementActions/)
  assert.match(actionsSource, /const updateRemoteProjectLinks = async \(projectId: string/)
  const bindingWriteCall = updateRemoteProjectLinksSource.indexOf('remoteDeviceBindingResolver.bindProjectToCurrentDevice(')
  const remoteUpdateCall = updateRemoteProjectLinksSource.indexOf('const updated = await options.remoteRepository.updateProject(projectId, input)')
  assert.notEqual(bindingWriteCall, -1)
  assert.notEqual(remoteUpdateCall, -1)
  assert.ok(remoteUpdateCall < bindingWriteCall)
  assert.match(updateRemoteProjectLinksSource, /databaseProfileId: settingsWorkspace\.selectedDatabaseProfileId/)
  assert.match(updateRemoteProjectLinksSource, /storageProfileId: settingsWorkspace\.selectedKodoProfileId/)
  assert.match(updateRemoteProjectLinksSource, /projectAssetObjectKeys\(remoteRows\)/)
  assert.match(remoteProfileActionsSource, /createProjectRemoteProfileVerificationActions/)
  assert.match(remoteProfileVerificationActionsSource, /verifyProjectDatabaseProfile/)
  assert.match(remoteProfileVerificationActionsSource, /initializeProjectDatabaseSchema/)
  assert.match(remoteProfileDeleteActionsSource, /deleteProjectConnectionProfile/)
  assert.match(remoteProfilesHookSource, /databaseSchemaReady/)
  assert.match(remoteProfileWorkspaceModelSource, /remoteReady: databaseReady && input\.databaseSchemaReady && kodoReady/)
  assert.match(remoteProfileVerificationActionsSource, /verifyProjectKodoProfile/)
  assert.match(remoteProfilesHookSource, /const selectDatabaseProfile = \(profileId: string\)/)
  assert.match(remoteProfilesHookSource, /const selectKodoProfile = \(profileId: string\)/)
  assert.match(remoteProfileDeleteActionsSource, /const deleteKodoProfile = async \(\)/)
  assert.match(remoteProfilesHookSource, /setKodoVerificationProjectId\(''\)/)
  assert.match(managementSurfaceSource, /onDeleteKodoProfile=\{\(\) => void workspace\.deleteKodoProfile\(\)\}/)
})

test('project management warns before leaving with unsaved changes', () => {
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementPanel.tsx', 'utf8')
  const panelWorkspaceHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectManagementPanelWorkspace.ts', 'utf8')
  const tabsSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementTabs.tsx', 'utf8')
  const createTabSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementCreateTab.tsx', 'utf8')
  const remoteSettingsSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteSettingsPanel.tsx', 'utf8')
  const remoteDatabaseSettingsSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteDatabaseSettingsPanel.tsx', 'utf8')
  const remoteProfileSaveButtonSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectRemoteProfileSaveButton.tsx', 'utf8')
  const remoteSettingsSectionSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementRemoteSettingsSection.tsx', 'utf8')
  const dirtyNavigationHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectManagementDirtyNavigation.ts', 'utf8')
  const dirtyModelSource = readFileSync('src/components/PersonalSpaceWorkspace/projectManagementDirtyModel.ts', 'utf8')
  const packageSource = packageJsonSource()

  assert.match(packageSource, /projectManagementDirtyModel\.test\.ts/)
  assert.match(dirtyModelSource, /ProjectManagementDirtySource/)
  assert.match(dirtyModelSource, /hasProjectManagementUnsavedChanges/)
  assert.match(dirtyModelSource, /projectManagementDirtySignature/)
  assert.match(panelSource, /useProjectManagementPanelWorkspace/)
  assert.match(panelWorkspaceHookSource, /useProjectManagementDirtyNavigation/)
  assert.doesNotMatch(panelSource, /useProjectManagementDirtyNavigation/)
  assert.doesNotMatch(panelSource, /projectManagementDirtyModel/)
  assert.doesNotMatch(panelSource, /hasProjectManagementUnsavedChanges/)
  assert.doesNotMatch(panelSource, /projectManagementDirtySignature/)
  assert.doesNotMatch(panelSource, /createCleanProjectManagementDirtyState/)
  assert.match(dirtyNavigationHookSource, /projectManagementDirtyModel/)
  assert.match(dirtyNavigationHookSource, /const hasUnsavedChanges = hasProjectManagementUnsavedChanges/)
  assert.match(dirtyNavigationHookSource, /const dirtySignature = projectManagementDirtySignature/)
  assert.match(panelSource, /requestBackToWorkbench/)
  assert.match(panelSource, /onClick=\{requestBackToWorkbench\}/)
  assert.doesNotMatch(panelSource, /onClick=\{onBack\}>返回工作台/)
  assert.doesNotMatch(panelSource, /window\.addEventListener\('beforeunload'/)
  assert.doesNotMatch(panelSource, /window\.removeEventListener\('beforeunload'/)
  assert.match(dirtyNavigationHookSource, /window\.addEventListener\('beforeunload'/)
  assert.match(dirtyNavigationHookSource, /window\.removeEventListener\('beforeunload'/)
  assert.match(panelSource, /open=\{leaveConfirmOpen\}/)
  assert.match(panelSource, /pendingProjectTabId/)
  assert.match(panelSource, /requestProjectTabChange/)
  assert.doesNotMatch(panelSource, /confirmDiscardAndSwitchTab/)
  assert.match(dirtyNavigationHookSource, /confirmDiscardAndSwitchTab/)
  assert.match(panelSource, /放弃更改/)
  assert.match(panelSource, /继续编辑/)
  assert.doesNotMatch(panelSource, /onChange=\{\(projectId\) => \{\s*resetAllDirtySources\(\)\s*onSelectedProjectChange\(projectId\)\s*\}\}/)
  assert.doesNotMatch(panelSource, /markDirty\('databaseProfileDraft'\)/)
  assert.doesNotMatch(panelSource, /markDirty\('kodoProfileDraft'\)/)
  assert.doesNotMatch(panelSource, /markDirty\(bindingDirtySource\)/)
  assert.match(remoteSettingsSectionSource, /markDirty\('databaseProfileDraft'\)/)
  assert.match(remoteSettingsSectionSource, /markDirty\('kodoProfileDraft'\)/)
  assert.match(remoteSettingsSectionSource, /markDirty\(bindingDirtySource\)/)
  assert.match(createTabSource, /bindingDirtySource="projectCreation"/)
  assert.match(createTabSource, /markDirty\('projectCreation'\)/)
  assert.match(tabsSource, /bindingDirtySource="remoteProjectBinding"/)
  assert.doesNotMatch(panelSource, /ProjectManagementRemoteSettingsSection/)
  assert.match(tabsSource, /ProjectManagementRemoteSettingsSection/)
  assert.match(remoteSettingsSource, /export function RemoteProjectSettings/)
  assert.match(remoteSettingsSource, /ProjectRemoteDatabaseSettingsPanel/)
  assert.match(remoteDatabaseSettingsSource, /保存当前数据库配置/)
  assert.match(remoteProfileSaveButtonSource, /failureDescription/)
  assert.doesNotMatch(panelSource, /InputNumber/)
})

test('project management delegates project detail draft workflow to a focused hook', () => {
  const hookPath = 'src/components/PersonalSpaceWorkspace/useProjectDetailsDraft.ts'
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementPanel.tsx', 'utf8')
  const panelWorkspaceHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectManagementPanelWorkspace.ts', 'utf8')
  const hookSource = existsSync(hookPath) ? readFileSync(hookPath, 'utf8') : ''

  assert.ok(existsSync(hookPath), 'project details draft hook should exist')
  assert.match(panelSource, /useProjectManagementPanelWorkspace/)
  assert.match(panelWorkspaceHookSource, /useProjectDetailsDraft/)
  assert.doesNotMatch(panelSource, /useProjectDetailsDraft/)
  assert.doesNotMatch(panelSource, /const \[projectNameDraft, setProjectNameDraft\]/)
  assert.doesNotMatch(panelSource, /const \[projectDescriptionDraft, setProjectDescriptionDraft\]/)
  assert.doesNotMatch(panelSource, /setProjectNameDraft\(selectedProject\?\.name/)
  assert.doesNotMatch(panelSource, /const editProject = async/)
  assert.match(hookSource, /useState\(selectedProject\?\.name/)
  assert.match(hookSource, /setProjectNameDraft\(selectedProject\?\.name/)
  assert.match(hookSource, /onRenameProject\(selectedProject\.id, projectNameDraft, projectDescriptionDraft\)/)
  assert.match(hookSource, /clearDirtySource\('projectDetails'\)/)
  assert.match(hookSource, /markDirty\('projectDetails'\)/)
})

test('project management panel delegates state orchestration to a workspace hook', () => {
  const hookPath = 'src/components/PersonalSpaceWorkspace/useProjectManagementPanelWorkspace.ts'
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementPanel.tsx', 'utf8')
  const hookSource = existsSync(hookPath) ? readFileSync(hookPath, 'utf8') : ''

  assert.ok(existsSync(hookPath), 'project management panel workspace hook should exist')
  assert.match(panelSource, /useProjectManagementPanelWorkspace/)
  assert.doesNotMatch(panelSource, /useProjectManagementDirtyNavigation/)
  assert.doesNotMatch(panelSource, /useProjectDetailsDraft/)
  assert.doesNotMatch(panelSource, /isRemoteProjectConfigurationReady/)
  assert.doesNotMatch(panelSource, /const remoteReadiness =/)
  assert.doesNotMatch(panelSource, /const remoteSettingsProps =/)
  assert.match(hookSource, /useProjectManagementDirtyNavigation/)
  assert.match(hookSource, /useProjectDetailsDraft/)
  assert.match(hookSource, /isRemoteProjectConfigurationReady/)
  assert.match(hookSource, /const remoteReadiness =/)
  assert.match(hookSource, /const remoteSettingsProps/)
})

test('project management shares remote readiness checks between panel and actions', () => {
  const packageSource = packageJsonSource()
  const modelPath = 'src/components/PersonalSpaceWorkspace/projectManagementModel.ts'
  const modelSource = existsSync(modelPath) ? readFileSync(modelPath, 'utf8') : ''
  const panelSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementPanel.tsx', 'utf8')
  const panelWorkspaceHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useProjectManagementPanelWorkspace.ts', 'utf8')
  const createTabSource = readFileSync('src/components/PersonalSpaceWorkspace/ProjectManagementCreateTab.tsx', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/projectManagementActions.ts', 'utf8')

  assert.ok(existsSync(modelPath), 'project management model should own shared readiness checks')
  assert.match(packageSource, /projectManagementModel\.test\.ts/)
  assert.match(modelSource, /function isRemoteProjectConfigurationReady/)
  assert.match(panelWorkspaceHookSource, /isRemoteProjectConfigurationReady/)
  assert.doesNotMatch(panelSource, /isRemoteProjectConfigurationReady/)
  assert.match(createTabSource, /isRemoteProjectConfigurationReady/)
  assert.match(actionsSource, /isRemoteProjectConfigurationReady/)
  assert.doesNotMatch(panelSource, /remoteReady && kodoVerificationProjectId ===/)
  assert.doesNotMatch(createTabSource, /remoteReady && remoteSettingsProps\.kodoVerificationProjectId ===/)
  assert.doesNotMatch(actionsSource, /kodoVerificationProjectId !==/)
})
