import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

test('project workspace startup resolves migrated projects from the remote repository first', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const sessionActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceProjectSessionActions.ts', 'utf8')
  const startupSource = readFileSync('src/components/PersonalSpaceWorkspace/projectWorkspaceStartup.ts', 'utf8')
  const activeProjectSource = readFileSync('src/components/ProjectStorage/projectActiveProject.ts', 'utf8')
  const activeProjectTestSource = readFileSync('src/components/ProjectStorage/projectActiveProject.test.ts', 'utf8')

  assert.match(workspaceSource, /createPersonalSpaceProjectSessionActions/)
  assert.match(sessionActionsSource, /from '\.\/projectWorkspaceStartup'/)
  assert.match(sessionActionsSource, /listProjectCatalogWithRemoteFallback/)
  assert.match(sessionActionsSource, /const localProjects = await options\.projectBootstrapper\.listProjects/)
  assert.match(sessionActionsSource, /remoteError/)
  assert.match(sessionActionsSource, /formatRemoteProjectListError/)
  assert.doesNotMatch(sessionActionsSource, /无法读取远程项目列表/)
  assert.doesNotMatch(sessionActionsSource, /remoteError instanceof Error \? remoteError\.message : String\(remoteError\)/)
  assert.match(startupSource, /mergeProjectsRemoteFirst/)
  assert.match(startupSource, /catch \(error\)/)
  assert.match(startupSource, /projects: localProjects/)
  assert.match(activeProjectSource, /export function mergeProjectsRemoteFirst/)
  assert.match(activeProjectTestSource, /prefers migrated remote projects over local snapshots with the same id/)
})

test('project workspace waits for remote connection profiles before startup remote reads', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const sessionActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceProjectSessionActions.ts', 'utf8')
  const settingsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceSettingsWorkspace.ts', 'utf8')
  const remoteProfilesHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useRemoteConnectionProfilesWorkspace.ts', 'utf8')
  const remoteProfileListsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/useRemoteConnectionProfileLists.ts', 'utf8')
  const lifecycleHookPath = 'src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceLifecycle.ts'
  const lifecycleHookSource = existsSync(lifecycleHookPath) ? readFileSync(lifecycleHookPath, 'utf8') : ''

  assert.match(settingsHookSource, /useRemoteConnectionProfilesWorkspace/)
  assert.match(remoteProfilesHookSource, /useRemoteConnectionProfileLists/)
  assert.match(remoteProfilesHookSource, /connectionProfilesLoaded/)
  assert.match(remoteProfileListsHookSource, /setConnectionProfilesLoaded\(true\)/)
  assert.match(sessionActionsSource, /if \(!options\.getSettingsWorkspace\(\)\.connectionProfilesLoaded\) return/)
  assert.ok(existsSync(lifecycleHookPath), `${lifecycleHookPath} should exist`)
  assert.match(workspaceSource, /from '\.\/usePersonalSpaceWorkspaceLifecycle'/)
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceLifecycle\(/)
  assert.match(lifecycleHookSource, /\}, \[settingsWorkspace\.connectionProfilesLoaded\]\)/)
  assert.match(sessionActionsSource, /listProjectCatalogWithRemoteFallback/)
  assert.match(sessionActionsSource, /void activateProjectStateFromStorage\(enabledProjectId, legacySpace, projects\)/)
})

test('personal space workspace delegates startup persistence and settings redirect effects', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const lifecycleHookPath = 'src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceLifecycle.ts'

  assert.ok(existsSync(lifecycleHookPath), `${lifecycleHookPath} should exist`)
  const lifecycleHookSource = readFileSync(lifecycleHookPath, 'utf8')

  assert.match(workspaceSource, /from '\.\/usePersonalSpaceWorkspaceLifecycle'/)
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceLifecycle\(/)
  assert.doesNotMatch(workspaceSource, /useEffect\(/)
  assert.doesNotMatch(workspaceSource, /writeProjectSpaceState\(activeProjectIdRef\.current, space\)/)
  assert.doesNotMatch(workspaceSource, /scheduleRemoteProjectSync\(space\)/)
  assert.doesNotMatch(workspaceSource, /setActiveModule\('settings'\)/)
  assert.match(lifecycleHookSource, /export function usePersonalSpaceWorkspaceLifecycle/)
  assert.match(lifecycleHookSource, /initializeProjects/)
  assert.match(lifecycleHookSource, /writeProjectSpaceState\(activeProjectIdRef\.current, space\)/)
  assert.match(lifecycleHookSource, /scheduleRemoteProjectSync\(space\)/)
  assert.match(lifecycleHookSource, /setActiveModule\('settings'\)/)
})

test('remote project activation restores workspace state from remote project rows', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const sessionActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceProjectSessionActions.ts', 'utf8')
  const activationActionsPath = 'src/components/PersonalSpaceWorkspace/personalSpaceProjectActivationActions.ts'
  const activationActionsSource = existsSync(activationActionsPath) ? readFileSync(activationActionsPath, 'utf8') : ''
  const persistenceSource = readFileSync('src/components/PersonalSpaceWorkspace/currentProjectSpacePersistence.ts', 'utf8')
  const loaderPath = 'src/components/PersonalSpaceWorkspace/currentProjectSpaceStateLoader.ts'

  assert.ok(existsSync(activationActionsPath), `${activationActionsPath} should exist`)
  assert.ok(existsSync(loaderPath), `${loaderPath} should exist`)
  const loaderSource = readFileSync(loaderPath, 'utf8')
  assert.match(workspaceSource, /createPersonalSpaceProjectSessionActions/)
  assert.match(sessionActionsSource, /from '\.\/personalSpaceProjectActivationActions'/)
  assert.match(sessionActionsSource, /createPersonalSpaceProjectActivationActions/)
  assert.doesNotMatch(sessionActionsSource, /loadProjectSpaceStateFromStorage/)
  assert.doesNotMatch(sessionActionsSource, /createEmptyProjectSpaceState/)
  assert.doesNotMatch(sessionActionsSource, /writeProjectSpaceState/)
  assert.match(activationActionsSource, /loadProjectSpaceStateFromStorage/)
  assert.match(activationActionsSource, /ensureRemoteSettings: options\.ensureRemoteProjectSettings/)
  assert.match(activationActionsSource, /onRemoteProjectLoaded: options\.rememberRemoteProjectSettings/)
  assert.match(activationActionsSource, /writeProjectSpaceState/)
  assert.match(activationActionsSource, /createEmptyProjectSpaceState/)
  assert.doesNotMatch(sessionActionsSource, /restoreProjectRowsToPersonalSpaceState/)
  assert.doesNotMatch(sessionActionsSource, /readCachedProjectSpaceState/)
  assert.match(persistenceSource, /from '\.\/currentProjectSpaceStateLoader'/)
  assert.doesNotMatch(persistenceSource, /restoreProjectRowsToPersonalSpaceState/)
  assert.doesNotMatch(persistenceSource, /readCachedProjectSpaceState/)
  assert.match(loaderSource, /export async function loadProjectSpaceStateFromStorage/)
  assert.match(loaderSource, /restoreProjectRowsToPersonalSpaceState/)
  assert.match(loaderSource, /readCachedProjectSpaceState/)
  assert.match(loaderSource, /formatRemoteProjectReadError/)
  assert.match(loaderSource, /asset\.primary_object_key/)
  assert.match(loaderSource, /asset\.sprite_index_object_key/)
  assert.match(loaderSource, /await options\.remoteRepository\.exportProjectRows/)
  assert.match(loaderSource, /await options\.localRepository\.importProjectRows/)
  assert.match(loaderSource, /writeProjectSpaceState\(options\.projectId, nextSpace, storage\)/)
  assert.match(sessionActionsSource, /void activateProjectStateFromStorage\(enabledProjectId, legacySpace, projects\)/)
  assert.match(sessionActionsSource, /void activateProjectStateFromStorage\(projectId\)/)
})

test('local project activation restores workspace state from local project rows', () => {
  const sessionActionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceProjectSessionActions.ts', 'utf8')
  const activationActionsPath = 'src/components/PersonalSpaceWorkspace/personalSpaceProjectActivationActions.ts'
  const activationActionsSource = existsSync(activationActionsPath) ? readFileSync(activationActionsPath, 'utf8') : ''
  const persistenceSource = readFileSync('src/components/PersonalSpaceWorkspace/currentProjectSpacePersistence.ts', 'utf8')
  const loaderSource = readFileSync('src/components/PersonalSpaceWorkspace/currentProjectSpaceStateLoader.ts', 'utf8')
  const persistenceTestSource = readFileSync('src/components/PersonalSpaceWorkspace/currentProjectSpaceLocalLoad.test.ts', 'utf8')

  assert.ok(existsSync(activationActionsPath), `${activationActionsPath} should exist`)
  assert.doesNotMatch(sessionActionsSource, /loadProjectSpaceStateFromStorage/)
  assert.match(activationActionsSource, /loadProjectSpaceStateFromStorage/)
  assert.doesNotMatch(sessionActionsSource, /restoreProjectRowsToPersonalSpaceState/)
  assert.match(persistenceSource, /from '\.\/currentProjectSpaceStateLoader'/)
  assert.match(loaderSource, /project\?\.mode === 'local'/)
  assert.match(loaderSource, /await options\.localRepository\.exportProjectRows\(options\.projectId\)/)
  assert.match(loaderSource, /restoreProjectRowsToPersonalSpaceState\(localRows\)/)
  assert.match(persistenceTestSource, /local project load restores workspace state from local project repository rows/)
})

test('personal space workspace delegates project management actions', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const workspaceActionsHookSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspaceActions.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/projectManagementActions.ts', 'utf8')
  const createActionsPath = 'src/components/PersonalSpaceWorkspace/projectManagementCreateActions.ts'
  const migrationActionSource = readFileSync('src/components/PersonalSpaceWorkspace/projectManagementMigrationAction.ts', 'utf8')
  const createActionsSource = existsSync(createActionsPath) ? readFileSync(createActionsPath, 'utf8') : ''
	
  assert.ok(existsSync(createActionsPath), 'project management create actions should exist')
  assert.match(workspaceSource, /usePersonalSpaceWorkspaceActions/)
  assert.match(workspaceActionsHookSource, /createProjectManagementActions/)
  assert.match(actionsSource, /export function createProjectManagementActions/)
  assert.match(actionsSource, /from '\.\/projectManagementCreateActions'/)
  assert.match(actionsSource, /createProjectManagementCreateActions\(options\)/)
  assert.match(actionsSource, /createLocalProject/)
  assert.match(actionsSource, /createRemoteProject/)
  assert.match(actionsSource, /renameProject/)
  assert.match(actionsSource, /updateRemoteProjectLinks/)
  assert.match(actionsSource, /deleteProject/)
  assert.match(actionsSource, /migrateActiveProjectToRemote/)
  assert.match(actionsSource, /hardDeleteProjectWithObjects/)
  assert.match(actionsSource, /createProjectManagementMigrationAction/)
  assert.match(migrationActionSource, /migrateLocalProjectToRemote/)
  assert.match(migrationActionSource, /remoteDeviceBindingResolver\.bindProjectToCurrentDevice/)
  assert.match(actionsSource, /remoteDeviceBindingResolver\.clearProjectFromCurrentDevice\(projectId\)/)
  assert.match(createActionsSource, /const createLocalProject = async/)
  assert.match(createActionsSource, /const createRemoteProject = async/)
  assert.match(createActionsSource, /options\.localRepository\.createProject/)
  assert.match(createActionsSource, /options\.remoteRepository\.createRemoteProject/)
  assert.doesNotMatch(actionsSource, /const createLocalProject = async/)
  assert.doesNotMatch(actionsSource, /const createRemoteProject = async/)
  assert.doesNotMatch(actionsSource, /options\.localRepository\.createProject/)
  assert.doesNotMatch(actionsSource, /options\.remoteRepository\.createRemoteProject/)
  assert.doesNotMatch(workspaceSource, /const createLocalProject = async/)
  assert.doesNotMatch(workspaceSource, /const createRemoteProject = async/)
  assert.doesNotMatch(workspaceSource, /const renameProject = async/)
  assert.doesNotMatch(workspaceSource, /const updateRemoteProjectLinks = async/)
  assert.doesNotMatch(workspaceSource, /const deleteProject = async/)
  assert.doesNotMatch(workspaceSource, /const migrateActiveProjectToRemote = async/)
})

test('personal space workspace delegates project session activation and navigation', () => {
  const workspaceSource = readFileSync('src/components/PersonalSpaceWorkspace/usePersonalSpaceWorkspace.ts', 'utf8')
  const actionsSource = readFileSync('src/components/PersonalSpaceWorkspace/personalSpaceProjectSessionActions.ts', 'utf8')

  assert.match(workspaceSource, /createPersonalSpaceProjectSessionActions/)
  assert.match(actionsSource, /export function createPersonalSpaceProjectSessionActions/)
  assert.match(actionsSource, /refreshProjectList/)
  assert.match(actionsSource, /activateProjectState/)
  assert.match(actionsSource, /activateProjectStateFromStorage/)
  assert.match(actionsSource, /enableProject/)
  assert.match(actionsSource, /disableActiveProject/)
  assert.match(actionsSource, /openProjectManagement/)
  assert.match(actionsSource, /closeProjectManagement/)
  assert.match(actionsSource, /changeActiveModule/)
  assert.match(actionsSource, /initializeProjects/)
  assert.doesNotMatch(workspaceSource, /const refreshProjectList = async/)
  assert.doesNotMatch(workspaceSource, /const activateProjectState = \(/)
  assert.doesNotMatch(workspaceSource, /const activateProjectStateFromStorage = async/)
  assert.doesNotMatch(workspaceSource, /const enableProject = \(/)
  assert.doesNotMatch(workspaceSource, /const disableActiveProject = \(/)
  assert.doesNotMatch(workspaceSource, /const openProjectManagement = \(/)
  assert.doesNotMatch(workspaceSource, /const closeProjectManagement = \(/)
  assert.doesNotMatch(workspaceSource, /const changeActiveModule = \(/)
})
