import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

test('voice deployment workspace delegates header service controls', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const panelSource = readFileSync('src/components/VoiceDeploymentWorkspace/VoiceSetupPanels.tsx', 'utf8')
  const headerPath = 'src/components/VoiceDeploymentWorkspace/VoiceWorkspaceHeader.tsx'

  assert.ok(existsSync(headerPath), 'voice workspace header should exist')
  const headerSource = readFileSync(headerPath, 'utf8')

  assert.match(source, /from '\.\/VoiceWorkspaceHeader'/)
  assert.match(source, /<VoiceWorkspaceHeader/)
  assert.doesNotMatch(source, /<Button\.Group className="voice-service-actions">/)
  assert.doesNotMatch(source, /className="voice-hero"/)
  assert.doesNotMatch(source, /addonBefore="端口"/)
  assert.match(headerSource, /connected \? \(/)
  assert.match(headerSource, /<Button\.Group className="voice-service-actions">/)
  assert.match(headerSource, /重新检测[\s\S]*重启服务[\s\S]*启动服务[\s\S]*停止服务/)
  assert.match(headerSource, /重启服务/)
  assert.match(headerSource, /启动服务/)
  assert.match(headerSource, /停止服务/)
  assert.match(headerSource, /controlDesktopService\('restart'\)/)
  assert.match(headerSource, /startDesktopService\(\)/)
  assert.doesNotMatch(headerSource, /controlDesktopService\('start'\)\.then\(\(\) => runCheck\(port\)\)/)
  assert.match(headerSource, /controlDesktopService\('stop'\)/)
  assert.match(headerSource, /desktopServiceBusy/)
  assert.match(headerSource, /desktopRuntime/)
  assert.match(headerSource, /addonBefore="端口"/)
  assert.doesNotMatch(panelSource, />\s*启动服务\s*</)
  assert.doesNotMatch(panelSource, />\s*停止服务\s*</)
  assert.doesNotMatch(panelSource, /查询状态/)
  assert.doesNotMatch(panelSource, /onControlDesktopService/)
})

test('voice deployment workspace delegates deployment setup state to a focused hook', () => {
  const source = readFileSync('src/components/VoiceDeploymentWorkspace/index.tsx', 'utf8')
  const workspaceHookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentWorkspace.ts', 'utf8')
  const hookSource = readFileSync('src/components/VoiceDeploymentWorkspace/useVoiceDeploymentSetup.ts', 'utf8')
  const serviceWorkflowSource = readFileSync('src/components/DesktopServiceRuntime/desktopServiceWorkflow.ts', 'utf8')

  assert.match(source, /from '\.\/useVoiceDeploymentWorkspace'/)
  assert.match(workspaceHookSource, /from '\.\/useVoiceDeploymentSetup'/)
  assert.match(workspaceHookSource, /useVoiceDeploymentSetup/)
  assert.doesNotMatch(source, /checkRef/)
  assert.doesNotMatch(source, /const runCheck = /)
  assert.doesNotMatch(source, /const applyPort = /)
  assert.doesNotMatch(source, /const hardwareReport = /)
  assert.doesNotMatch(source, /const oneClickCommand = /)
  assert.doesNotMatch(source, /const apiCallExample = /)
  assert.doesNotMatch(source, /checkConnection/)
  assert.match(hookSource, /checkRef/)
  assert.match(hookSource, /runCheck/)
  assert.match(hookSource, /applyPort/)
  assert.doesNotMatch(hookSource, /deviceType/)
  assert.doesNotMatch(hookSource, /gpuInput/)
  assert.match(hookSource, /parseNvidiaSmiReport/)
  assert.match(hookSource, /evaluateHardware/)
  assert.match(hookSource, /detectDesktopHardware/)
  assert.match(hookSource, /runDesktopSetup/)
  assert.match(hookSource, /startDesktopService/)
  assert.match(hookSource, /waitForDesktopServiceConnection/)
  assert.match(hookSource, /queryVoxcpmSetupStatus/)
  assert.doesNotMatch(hookSource, /依赖安装未完成/)
  assert.match(serviceWorkflowSource, /依赖安装未完成/)
  assert.match(hookSource, /controlDesktopService/)
  assert.doesNotMatch(hookSource, /oneClickCommand/)
  assert.match(hookSource, /apiCallExample/)
  assert.match(hookSource, /checkConnection/)
})
