import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { imageProcessingStyleSources } from '../../appStructureTestHelpers.test'

test('image processing workspace keeps crop result stage on the right and controls on the left', () => {
  const source = readFileSync('src/components/ImageProcessingWorkspace/index.tsx', 'utf8')
  const sideStart = source.indexOf('<div className="image-processing-side">')
  const mainStart = source.indexOf('<div className="image-processing-main">')
  const sideSource = source.slice(sideStart, mainStart)
  const mainSource = source.slice(mainStart)

  assert.notEqual(sideStart, -1)
  assert.notEqual(mainStart, -1)
  assert.match(sideSource, /<Tabs/)
  assert.match(sideSource, /items=\{controlTabs\}/)
  assert.match(source, /key: 'matte'[\s\S]*<ImageMattePanel workspace=\{workspace\} \/>/)
  assert.match(source, /key: 'crop'[\s\S]*<ImageCropPanel workspace=\{workspace\} \/>/)
  assert.match(source, /key: 'export'[\s\S]*<ImageExportPanel workspace=\{workspace\} \/>/)
  assert.match(mainSource, /<ImageCropResultStage workspace=\{workspace\} \/>/)
  assert.doesNotMatch(mainSource, /<ImageCropPanel workspace=\{workspace\} \/>/)
  assert.doesNotMatch(sideSource, /<ImageCropResultStage workspace=\{workspace\} \/>/)
})

test('image processing workspace uses compact toolbar, tabbed controls, and stable result stage', () => {
  const source = readFileSync('src/components/ImageProcessingWorkspace/index.tsx', 'utf8')
  const toolbarSource = readFileSync('src/components/ImageProcessingWorkspace/ImageProcessingToolbar.tsx', 'utf8')
  const statusSource = readFileSync('src/components/ImageProcessingWorkspace/ImageProcessingStatusBar.tsx', 'utf8')
  const cssSource = imageProcessingStyleSources()

  assert.match(source, /<ImageProcessingToolbar workspace=\{workspace\} \/>/)
  assert.match(source, /<Tabs[\s\S]*items=\{controlTabs\}/)
  assert.match(source, /key: 'matte'[\s\S]*<ImageMattePanel workspace=\{workspace\} \/>/)
  assert.match(source, /key: 'crop'[\s\S]*<ImageCropPanel workspace=\{workspace\} \/>/)
  assert.match(source, /key: 'export'[\s\S]*<ImageExportPanel workspace=\{workspace\} \/>/)
  assert.match(source, /<ImageProcessingStatusBar workspace=\{workspace\} \/>/)
  assert.doesNotMatch(source, /<ImageUploadPanel workspace=\{workspace\} \/>[\s\S]*<ImageMattePanel workspace=\{workspace\} \/>[\s\S]*<ImageCropPanel workspace=\{workspace\} \/>[\s\S]*<ImageExportPanel workspace=\{workspace\} \/>/)
  assert.match(toolbarSource, /className="image-processing-toolbar"/)
  assert.match(toolbarSource, /ImageUploadPanel/)
  assert.match(toolbarSource, /variant="compact"/)
  assert.match(statusSource, /className="image-processing-status"/)
  assert.match(statusSource, /源图/)
  assert.match(statusSource, /裁剪/)
  assert.match(statusSource, /导出/)
  assert.match(cssSource, /height:\s*calc\(100vh - [^)]+px\)/)
  assert.match(cssSource, /min-height:\s*\d+px/)
})

test('image crop panel owns crop aspect ratio while export panel scales locked output size', () => {
  const cropSource = readFileSync('src/components/ImageProcessingWorkspace/ImageCropPanel.tsx', 'utf8')
  const exportSource = readFileSync('src/components/ImageProcessingWorkspace/ImageExportPanel.tsx', 'utf8')

  assert.match(cropSource, /title=\{cropPanelTitle\}/)
  assert.match(cropSource, /裁剪框居中/)
  assert.match(cropSource, /centerCropBox/)
  assert.match(cropSource, /value=\{workspace\.cropAspectRatio\}/)
  assert.match(cropSource, /onCommit=\{workspace\.updateCropAspectRatio\}/)
  assert.match(exportSource, /value=\{workspace\.exportScale\}/)
  assert.match(exportSource, /onCommit=\{workspace\.setExportScale\}/)
  assert.match(exportSource, /value=\{workspace\.exportSize\.width\}/)
  assert.match(exportSource, /value=\{workspace\.exportSize\.height\}/)
  assert.match(exportSource, /onCommit=\{\(value\) => workspace\.updateExportDimension\('width', value\)\}/)
  assert.match(exportSource, /onCommit=\{\(value\) => workspace\.updateExportDimension\('height', value\)\}/)
  assert.doesNotMatch(exportSource, /onChange=\{workspace\.updateCropAspectRatio\}/)
  assert.doesNotMatch(exportSource, /updateExportAspectRatio/)
  assert.doesNotMatch(exportSource, /setExportAspectLocked/)
  assert.doesNotMatch(exportSource, /addonAfter/)
})

test('image processing result stage delegates preview DOM interactions to a focused hook', () => {
  const stageSource = readFileSync('src/components/ImageProcessingWorkspace/ImageCropResultStage.tsx', 'utf8')
  const hookPath = 'src/components/ImageProcessingWorkspace/useImagePreviewStageInteractions.ts'
  const cssSource = imageProcessingStyleSources()

  assert.ok(existsSync(hookPath), 'image preview stage interactions hook should exist')
  const hookSource = readFileSync(hookPath, 'utf8')

  assert.match(stageSource, /from '\.\/useImagePreviewStageInteractions'/)
  assert.match(stageSource, /useImagePreviewStageInteractions/)
  assert.doesNotMatch(stageSource, /ResizeObserver/)
  assert.doesNotMatch(stageSource, /addEventListener\('wheel'/)
  assert.doesNotMatch(stageSource, /getPreviewAnchorFromStagePoint/)
  assert.doesNotMatch(stageSource, /dataTransfer\.files/)
  assert.doesNotMatch(stageSource, /workspace\.uploadImage/)
  assert.doesNotMatch(stageSource, /setDragDepth/)
  assert.match(stageSource, /onDragEnter/)
  assert.match(stageSource, /onDragOver/)
  assert.match(stageSource, /onDragLeave/)
  assert.match(stageSource, /onDrop/)
  assert.match(stageSource, /拖入图片添加到待处理列表/)
  assert.match(hookSource, /export function useImagePreviewStageInteractions/)
  assert.match(hookSource, /ResizeObserver/)
  assert.match(hookSource, /addEventListener\('wheel'/)
  assert.match(hookSource, /getPreviewAnchorFromStagePoint/)
  assert.match(hookSource, /dataTransfer\.files/)
  assert.match(hookSource, /uploadImages\(files\)/)
  assert.match(cssSource, /image-preview-drop-overlay/)
})
